In [2]:
import pandas as pd
import numpy as np

In [3]:
data_ap = pd.read_excel('9월20일_RADIUS_ACCOUNT_로그.xlsx')

In [4]:
data_ap1 = pd.read_excel('9월21일_RADIUS_ACCOUNT_로그.xlsx')

In [5]:
data_ap2 = pd.read_excel('9월22일_RADIUS_ACCOUNT_로그.xlsx')

In [6]:
data_ap3 = pd.read_excel('9월23일_RADIUS_ACCOUNT_로그.xlsx')

In [7]:
data_ap4 = pd.read_excel('9월24일_RADIUS_ACCOUNT_로그.xlsx')

In [8]:
ap_data = pd.concat([data_ap,data_ap1,data_ap2,data_ap3,data_ap4], axis = 0)

In [9]:
ap_data.shape

(289583, 27)

In [10]:
ap_data.head(5)

,jnuradacctid,acctsessionid,acctuniqueid,username,groupname,realm,nasipaddress,nasportid,nasporttype,acctstarttime,...,calledstationid,callingstationid,acctterminatecause,servicetype,framedprotocol,framedipaddress,acctstartdelay,acctstopdelay,xascendsessionsvrkey,server
0,80667358,00001E01-000003A1,0fe18110b0c97807245b9ba59247d171,193611,NaN,NaN,168.131.13.224,0.0,Wireless-802.11,2019-09-20 00:29:11,...,F4-D9-FB-E3-0A-6F:JNU,74-B5-87-8B-E5-61,NaN,NaN,NaN,10.10.45.229,0,0,NaN,168.131.33.63
1,80667445,00002201-0000092D,cdca1be343c6ef24b5e03f27f5659014,175311,NaN,NaN,168.131.13.224,0.0,Wireless-802.11,2019-09-20 00:33:28,...,F4-D9-FB-E3-BF-8F:JNU,94-8B-C1-51-F5-3A,NaN,NaN,NaN,10.10.59.240,0,0,NaN,168.131.33.63
2,80667446,00002201-0000092E,1a7551d4aec7d35ee4d659bea0ae9772,150850,NaN,NaN,168.131.13.224,0.0,Wireless-802.11,2019-09-20 01:28:49,...,F4-D9-FB-E3-BF-8F:JNU,D0-B1-28-BA-00-6F,NaN,NaN,NaN,10.10.34.83,0,0,NaN,168.131.33.63
3,80667513,00002801-00000470,977346d2dd8a9ba2d2eb0a07c9c81541,192777,NaN,NaN,168.131.13.224,0.0,Wireless-802.11,2019-09-20 00:25:53,...,F4-D9-FB-E3-0A-20:JNU,08-AE-D6-30-A0-33,NaN,NaN,NaN,10.10.12.83,0,0,NaN,168.131.33.63
4,80667615,00002A01-000012F1,65e89d358a61b1d65fb26dcae1eaa266,171959,NaN,NaN,168.131.13.224,0.0,Wireless-802.11,2019-09-20 00:24:17,...,F4-D9-FB-E3-0A-2F:JNU,84-41-67-CA-A4-F1,NaN,NaN,NaN,10.10.43.183,0,0,NaN,168.131.33.63

In [11]:
ap_data.to_excel('LOG_CONCAT.xlsx',sheet_name='Sheet1')

In [12]:
ap_data = ap_data.iloc[:,[3,4,7,10,11,12,19,22]]
data_df.head(3)

NameError: name 'data_df' is not defined

In [14]:
data_df[data_df['ap_ip'] == '168.131.61.236']

Empty DataFrame
Columns: [username, username_hash, ap_ip, 사용시작시각, 사용종료시각, 사용시간, 단말기_mac , 단말기_ip]
Index: []

In [15]:
data_df.shape

(9917439, 8)

In [16]:
data_null = data_df[data_df['사용종료시각'].isnull() == False]
data_null.shape

(1644537, 8)

In [17]:
data_null['ap_ip'].value_counts()

168.131.13.221    552958
168.131.13.220    459128
168.131.13.226    104980
168.131.13.225     50172
14.48.182.43       40208
                   ...
10.40.17.4             1
10.200.2.14            1
10.40.9.25             1
192.168.180.22         1
10.40.33.89            1
Name: ap_ip, Length: 132, dtype: int64

In [18]:
data_df[data_df['사용종료시각'].isnull() == True]

,username,username_hash,ap_ip,사용시작시각,사용종료시각,사용시간,단말기_mac,단말기_ip
1096,133327,0xDB7DD9484863DA7C9274028288EFA1B522074723,168.131.13.221,2017-11-21 10:16:37.000,NaN,0.0,68DBCAC5D26A,168.131.188.197
2880,171039,0x10277356A2ADB7EF598ED49D9C66F09389A175FA,168.131.13.220,2017-11-21 10:27:53.000,NaN,5079.0,D013FD37A0F7,168.131.209.136
6353,108034,0x0730D1335797834DF433B79EFEF4CF0EDA0033F7,168.131.13.221,2017-11-21 11:21:01.000,NaN,52203.0,ACEE9ED5C017,168.131.215.156
9189,161453,0xE208216B60FA62EBE5E0F68D7B5AE50A23DA19DD,168.131.13.220,2017-11-21 11:53:37.000,NaN,0.0,440010B66FAA,168.131.202.74
16803,115216,0x35353748483BB5C0B1EAAEB13D079D57738E59B7,14.48.181.17,2017-11-21 13:27:32.000,NaN,0.0,F0-79-60-34-94-27,NaN
17681,kimis,0xCD58D4CCF843E3EC5EAF7210839940FA935ACB92,168.131.13.221,2017-11-21 13:33:10.000,NaN,44591.0,C4850874A5EA,168.131.174.226
18228,131354,0xA049BB4E57709BF6888E14EFEAB918F79340FF58,168.131.13.221,2017-11-21 13:38:41.000,NaN,44154.0,DC0B34DF7AAA,168.131.215.73
19256,154985,0x0648CE7D298AA9E8B7B73FD449B2F3AE49C31ADB,168.131.13.221,2017-11-21 13:54:17.000,NaN,0.0,6C19C0A5292E,168.131.196.160
19728,120941,0xCB4E2FECE7BEED8CFDDE57AEBFF3E4447856681F,168.131.13.220,2017-11-21 14:02:44.000,NaN,42523.0,ACAFB9BB3574,168.131.203.168
20276,167941,0xF310DAA205C8BE826A6BF01AE8A9D737795CCA65,14.48.182.43,2017-11-21 14:12:04.000,NaN,0.0,10-41-7F-53-DF-CE,NaN
22210,85599,0x77DB3D87E10A698012367A9273A5AF4C7CB7DCD0,168.131.13.220,2017-11-21 14:42:59.000,NaN,0.0,90FD610527D7,168.131.208.127
22657,134032,0x01D2D4D74EA86898ABF93B833001633EED0C53C2,168.131.13.221,2017-11-21 14:46:13.000,NaN,0.0,748D086122E3,168.131.214.240
22871,123149,0x0C140D996587ABB4E741E904FC1E119C152687A0,168.131.13.221,2017-11-21 14:47:28.000,NaN,40097.0,780CB80DC26C,168.131.216.45
25135,111644,0x1025F0EA4152995F37FD08C0A6633E6942260A30,168.131.13.220,2017-11-21 15:01:30.000,NaN,329.0,3035AD4320FA,168.131.198.153
25209,123419,0x58D185051C28B981F6E85191DE462ECD14149CF7,14.48.182.49,2017-11-21 15:02:05.000,NaN,0.0,AC-EE-9E-FE-E1-2D,NaN
26307,122844,0x7B37E764AC010516A750D93F1C901082AB8DEE9D,168.131.13.220,2017-11-21 15:15:40.000,NaN,1988.0,CC29F5D36427,168.131.207.113
26426,156832,0x8A1E27FD5F6746A5DE7528DC2304CB2F0D3922F9,168.131.13.221,2017-11-21 15:18:07.000,NaN,0.0,440010B6730E,168.131.189.161
28529,153143,0x0D7FA847A0A0EEB45830B8D2DC3B5B428FB59483,168.131.13.220,2017-11-21 15:58:21.000,NaN,0.0,484BAA9C01E9,168.131.204.51
28918,mongju,0x9A0491A6E88C3E7C642286A6BDE2F142D0806E8C,168.131.13.221,2017-11-21 16:05:02.000,NaN,0.0,948BC103202E,168.131.158.53
29717,123284,0x9BB8014491BC56F4FD9F93111125A7A4AF774A7C,168.131.13.221,2017-11-21 16:14:57.000,NaN,34883.0,80000B0723C6,168.131.194.28
30473,153362,0x5BB036C8333C8749DD34CA82C74A993213BD675C,14.48.182.44,2017-11-21 16:20:21.000,NaN,0.0,90-B0-ED-80-5E-9C,NaN
32373,ojh,0xEE36769F721CF8EAF6D382069746E698467C8206,168.131.13.221,2017-11-21 16:39:20.000,NaN,33138.0,849866858E03,168.131.174.198
33553,b7931,0xC426EF6FE5CBD0B51E27FFF594487725D947E0F1,168.131.13.220,2017-11-21 17:02:36.000,NaN,3526.0,94D771E84627,168.131.206.58
34172,sjunkim,0xE2CAB9DB1370589C21E038181C6AEE38881274CE,168.131.13.220,2017-11-21 17:18:21.000,NaN,31209.0,B827EB6A7B8A,168.131.210.28
34283,145134,0x87F04A6CBC43D24A34B59B76E4F4DDF5C3B6E92A,168.131.13.220,2017-11-21 17:21:01.000,NaN,31087.0,34BE00B26EA6,168.131.197.19
34359,166456,0xB464686395FA88609BA4DDEAE1F83D72BA5D20E8,168.131.13.221,2017-11-21 17:22:54.000,NaN,30524.0,0CD2922E8F38,168.131.175.38
34467,176113,0xEFB2E1E11B64B1352DA50E2054920B2B059A97F1,168.131.13.221,2017-11-21 17:24:59.000,NaN,30540.0,80A589203BD3,168.131.174.107
34554,157961,0x387FB94C7C4152F758A83D46470BEFB73BC82E0C,168.131.13.220,2017-11-21 17:27:04.000,NaN,30687.0,64899A51E83A,168.131.203.97
35151,167709,0x0C461B09BB77C4E4762E509E37375E015C68FB9E,168.131.13.221,2017-11-21 17:38:17.000,NaN,29777.0,5CE8EB32D457,168.131.157.67
38585,wookiya,0x9DEE9B06C6303858F3583ADB06EF5FACA0BD5290,168.131.13.221,2017-11-21 18:52:05.000,NaN,25385.0,B0DF3A7E2142,168.131.174.18
...,...,...,...,...,...,...,...,...
9917409,187374,0xF05E631571FFA3B7378C6489850B4A24D2464F70,168.131.13.226,NaN,NaN,12.0,D02598B8D6A9,168.131.204.70
9917410,187374,0xF05E631571FFA3B7378C6489850B4A24D2464F70,168.131.13.221,NaN,NaN,36.0,D02598B8D6A9,168.131.195.14
9917411,187374,0xF05E631571FFA3B7378C6489850B4A24D2464F70,168.131.13.221,NaN,NaN,49.0,D02598B8D6A9,168.131.195.35
9917412,187374,0xF05E631571FFA3B7378C6489850B4A24D2464F70,168.131.13.221,NaN,NaN,3327.0,D02598B8D6A9,168.131.195.70
9917413,187374,0xF05E631571FFA3B7378C6489850B4A24D2464F70,168.131.13.221,NaN,NaN,215.0,D02598B8D6A9,168.131.195.70
9917414,187397,0xA4272E5824CA462A11D38C9CBDEFE5F26DB470E7,168.131.13.226,NaN,NaN,33375.0,9822EF973A11,168.131.204.13
9917415,187397,0xA4272E5824CA462A11D38C9CBDEFE5F26DB470E7,168.131.13.221,NaN,NaN,83.0,9822EF973A11,168.131.189.12
9917416,187397,0xA4272E5824CA462A11D38C9CBDEFE5F26DB470E7,168.131.13.221,NaN,NaN,562.0,9822EF973A11,168.131.189.25
9917417,187397,0xA4272E5824CA462A11D38C9CBDEFE5F26DB470E7,168.131.13.226,NaN,NaN,13146.0,A48431E944D2,168.131.207.24
9917418,187397,0xA4272E5824CA462A11D38C9CBDEFE5F26DB470E7,168.131.13.226,NaN,NaN,17904.0,A48431E944D2,168.131.207.65
9917419,187398,0x2748247FDFBBE156F978706D423412BEE090A116,168.131.13.221,NaN,NaN,6282.0,9487E0460FE8,168.131.195.57
9917420,187398,0x2748247FDFBBE156F978706D423412BEE090A116,168.131.13.221,NaN,NaN,6155.0,9487E0460FE8,168.131.195.31
9917421,187408,0xA1EBAECBBE70084CCBEE856A98E45BE0B5D825EE,168.131.13.226,NaN,NaN,378.0,9C2EA19CA17F,168.131.206.13
9917422,187408,0xA1EBAECBBE70084CCBEE856A98E45BE0B5D825EE,168.131.13.221,NaN,NaN,4966.0,9C2EA19CA17F,168.131.194.60
9917423,187408,0xA1EBAECBBE70084CCBEE856A98E45BE0B5D825EE,168.131.13.221,NaN,NaN,565.0,9C2EA19CA17F,168.131.194.60
9917424,187413,0xA6DA3DBC9C730F12D191F1544E3C63DAA3343666,168.131.13.226,NaN,NaN,105.0,484BAA4B6AED,168.131.205.61
9917425,187413,0xA6DA3DBC9C730F12D191F1544E3C63DAA3343666,168.131.13.221,NaN,NaN,20.0,484BAA4B6AED,192.168.10.66
9917426,187442,0x48B11FFE1713C2CD972E482B42681D64B8CD33E6,168.131.13.226,NaN,NaN,0.0,685ACF96713E,168.131.203.75
9917427,187442,0x48B11FFE1713C2CD972E482B42681D64B8CD33E6,168.131.13.226,NaN,NaN,89.0,685ACF96713E,168.131.174.146
9917428,187442,0x48B11FFE1713C2CD972E482B42681D64B8CD33E6,168.131.13.226,NaN,NaN,555.0,685ACF96713E,10.10.39.233
9917429,187442,0x48B11FFE1713C2CD972E482B42681D64B8CD33E6,168.131.13.221,NaN,NaN,0.0,685ACF96713E,168.131.174.58
9917430,187442,0x48B11FFE1713C2CD972E482B42681D64B8CD33E6,168.131.13.221,NaN,NaN,10136.0,685ACF96713E,10.10.23.219
9917431,187457,0x75F511B8BCDCABE2B9FD7DADE9F48AD89F3D1BED,168.131.13.226,NaN,NaN,869.0,94EBCDF6FD7C,168.131.203.13
9917432,187457,0x75F511B8BCDCABE2B9FD7DADE9F48AD89F3D1BED,168.131.13.226,NaN,NaN,0.0,94EBCDF6FD7C,168.131.199.111
9917433,187457,0x75F511B8BCDCABE2B9FD7DADE9F48AD89F3D1BED,168.131.13.226,NaN,NaN,18.0,94EBCDF6FD7C,168.131.203.29
9917434,187457,0x75F511B8BCDCABE2B9FD7DADE9F48AD89F3D1BED,168.131.13.226,NaN,NaN,27.0,94EBCDF6FD7C,168.131.203.17
9917435,187457,0x75F511B8BCDCABE2B9FD7DADE9F48AD89F3D1BED,168.131.13.226,NaN,NaN,72.0,94EBCDF6FD7C,10.10.22.146
9917436,187457,0x75F511B8BCDCABE2B9FD7DADE9F48AD89F3D1BED,168.131.13.221,NaN,NaN,4009.0,94EBCDF6FD7C,168.131.216.168
9917437,187457,0x75F511B8BCDCABE2B9FD7DADE9F48AD89F3D1BED,168.131.13.221,NaN,NaN,530.0,94EBCDF6FD7C,168.131.216.12
9917438,187457,0x75F511B8BCDCABE2B9FD7DADE9F48AD89F3D1BED,168.131.13.221,NaN,NaN,16031.0,94EBCDF6FD7C,168.131.216.12

In [19]:
data_df[data_df['사용시간'].isnull() == True]

,username,username_hash,ap_ip,사용시작시각,사용종료시각,사용시간,단말기_mac,단말기_ip
1251453,wtest,0x2D91CD98D34570B19F970B7A23BC81FF1E7DA8E2,192.168.6.34,NaN,NaN,NaN,5C-70-A3-21-5C-67,NaN
1255781,wtest,0x2D91CD98D34570B19F970B7A23BC81FF1E7DA8E2,192.168.6.34,NaN,NaN,NaN,58-40-4E-D1-A3-63,NaN
1255782,wtest,0x2D91CD98D34570B19F970B7A23BC81FF1E7DA8E2,192.168.6.34,NaN,NaN,NaN,5C-70-A3-21-5C-67,NaN
1256246,wtest,0x2D91CD98D34570B19F970B7A23BC81FF1E7DA8E2,192.168.6.34,NaN,NaN,NaN,58-40-4E-D1-A3-63,NaN
1256476,wtest,0x2D91CD98D34570B19F970B7A23BC81FF1E7DA8E2,192.168.6.34,NaN,NaN,NaN,5C-70-A3-21-5C-67,NaN
1276123,wtest,0x2D91CD98D34570B19F970B7A23BC81FF1E7DA8E2,192.168.6.34,NaN,NaN,NaN,5C-70-A3-21-5C-67,NaN
1291713,wtest,0x2D91CD98D34570B19F970B7A23BC81FF1E7DA8E2,192.168.6.34,NaN,NaN,NaN,58-40-4E-D1-A3-63,NaN
1291715,wtest,0x2D91CD98D34570B19F970B7A23BC81FF1E7DA8E2,192.168.6.34,NaN,NaN,NaN,5C-70-A3-21-5C-67,NaN
1293351,wtest,0x2D91CD98D34570B19F970B7A23BC81FF1E7DA8E2,192.168.6.34,NaN,NaN,NaN,58-40-4E-D1-A3-63,NaN
1294257,wtest,0x2D91CD98D34570B19F970B7A23BC81FF1E7DA8E2,192.168.6.34,NaN,NaN,NaN,5C-70-A3-21-5C-67,NaN
8630326,wtest,0x2D91CD98D34570B19F970B7A23BC81FF1E7DA8E2,10.202.7.138,NaN,NaN,NaN,68-DB-CA-D2-BA-AD,NaN