In [10]:
import tensorflow as tf
#Data Manipulation
import numpy as np
import pandas as pd

#Visualization
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

#Importing Dependencies
%matplotlib inline

import math

In [12]:
#액셀파일 열기
data = pd.read_excel('ap.xlsx',sheet_name='AP사용정보')
data.head(3)

,USER_TYPE,AP IP주소,AP가 설치된 건물-층,"위도,경도",AP_TYPE,START_USING_TIME,END_USING_TIME,USAGE_TIME(second),AP_MAC -SHA256해쉬값전환,사용자단말 MAC-SHA256해쉬값전환
0,학생,168.131***,기초특성화과학관-7층,"35.175860, 126.911051",전남대AP,2019-05-01 00:21:43,2019-05-01 01:06:38,2693,qqGqT,1V/2G
1,학생,168.131***,기초특성화과학관-1층,"35.175860, 126.911051",전남대AP,2019-05-01 00:28:32,2019-05-01 00:29:06,34,9REc7,iA07F
2,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 01:09:34,2019-05-01 01:12:17,162,LbvpW,MJj9o

In [14]:
data_ap = data.loc[(data['AP가 설치된 건물-층']=="명학회관-4층"),:]
data_ap.head(50)

,USER_TYPE,AP IP주소,AP가 설치된 건물-층,"위도,경도",AP_TYPE,START_USING_TIME,END_USING_TIME,USAGE_TIME(second),AP_MAC -SHA256해쉬값전환,사용자단말 MAC-SHA256해쉬값전환
2,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 01:09:34,2019-05-01 01:12:17,162,LbvpW,MJj9o
3,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 01:17:53,2019-05-01 04:34:40,11807,zx3M1,WrRdn
5,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 02:56:39,2019-05-01 02:57:05,25,zx3M1,MJj9o
7,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 04:16:53,2019-05-01 07:49:18,12745,zx3M1,1ADFm
9,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 04:59:25,2019-05-01 08:48:11,13727,zx3M1,WrRdn
13,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 08:09:47,2019-05-01 08:10:01,13,zx3M1,1ADFm
15,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 08:10:01,2019-05-01 17:13:44,32623,zx3M1,1ADFm
30,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 08:52:34,2019-05-01 08:52:34,0,zx3M1,VacMg
31,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 08:52:35,2019-05-01 08:58:12,337,zx3M1,VacMg
35,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 08:53:13,2019-05-01 08:58:18,305,LbvpW,VacMg
188,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 10:26:08,2019-05-01 10:31:05,308,zx3M1,ktKxc
190,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 10:27:49,2019-05-01 10:29:46,117,LbvpW,ktKxc
192,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 10:29:47,2019-05-01 10:35:08,321,LbvpW,ktKxc
277,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 11:24:03,2019-05-01 11:24:32,29,LbvpW,pmxX2
320,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 11:54:33,2019-05-01 11:55:27,54,zx3M1,ktKxc
321,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 11:55:28,2019-05-01 11:55:29,1,zx3M1,ktKxc
322,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 11:55:56,2019-05-01 11:55:57,1,zx3M1,ktKxc
323,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 11:56:04,2019-05-01 11:56:05,1,zx3M1,ktKxc
336,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 11:59:09,2019-05-01 12:08:30,561,zx3M1,ktKxc
349,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:04:22,2019-05-01 12:04:31,9,LbvpW,5vcXf
350,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:06:20,2019-05-01 12:11:42,322,LbvpW,WrRdn
353,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:07:47,2019-05-01 12:09:44,117,LbvpW,0KGF6
354,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:07:51,2019-05-01 12:14:46,415,zx3M1,0KGF6
355,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:08:32,2019-05-01 12:09:43,71,zx3M1,ktKxc
357,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:09:44,2019-05-01 12:15:43,358,LbvpW,0KGF6
358,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:09:44,2019-05-01 12:09:45,1,zx3M1,ktKxc
360,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:10:01,2019-05-01 12:12:33,151,zx3M1,ktKxc
364,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:12:34,2019-05-01 12:13:34,59,zx3M1,ktKxc
365,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:13:36,2019-05-01 12:14:55,79,zx3M1,ktKxc
366,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:14:57,2019-05-01 12:20:29,332,zx3M1,ktKxc
373,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:20:30,2019-05-01 12:21:30,60,zx3M1,ktKxc
376,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:21:32,2019-05-01 12:22:25,53,zx3M1,ktKxc
377,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:21:52,2019-05-01 12:22:07,15,zx3M1,WrRdn
379,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:22:26,2019-05-01 12:22:27,0,zx3M1,ktKxc
381,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:23:41,2019-05-01 12:25:21,100,zx3M1,ktKxc
384,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:25:22,2019-05-01 12:26:41,78,zx3M1,ktKxc
387,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:26:42,2019-05-01 12:26:52,11,zx3M1,ktKxc
389,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:26:54,2019-05-01 12:27:51,57,zx3M1,ktKxc
392,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:27:52,2019-05-01 12:27:57,5,zx3M1,ktKxc
393,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:27:58,2019-05-01 12:31:30,212,zx3M1,ktKxc
397,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:31:31,2019-05-01 12:32:06,34,zx3M1,ktKxc
398,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:32:08,2019-05-01 12:32:09,1,zx3M1,ktKxc
400,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:34:14,2019-05-01 12:34:45,31,zx3M1,ktKxc
401,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:34:46,2019-05-01 12:34:47,1,zx3M1,ktKxc
403,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:36:12,2019-05-01 12:38:57,165,zx3M1,ktKxc
410,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:38:58,2019-05-01 12:40:45,107,zx3M1,ktKxc
413,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:40:47,2019-05-01 12:41:16,30,zx3M1,ktKxc
415,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:41:18,2019-05-01 12:42:57,99,zx3M1,ktKxc
421,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:42:59,2019-05-01 12:42:59,1,zx3M1,ktKxc
422,학생,14.48.1***,명학회관-4층,"35.141651, 126.923151",통신사AP,2019-05-01 12:43:39,2019-05-01 12:44:18,40,zx3M1,ktKxc

In [16]:
data_ap.describe()

       USAGE_TIME(second)
count         8570.000000
mean          1556.874912
std           7880.791557
min              0.000000
25%             32.000000
50%            314.000000
75%            397.000000
max         234588.000000

In [ ]:
data_ap.dtypes

In [1]:
data_ap.tail(20)
data_ap.reset_index(drop=True)

NameError: name 'data_ap' is not defined

In [9]:
import pandas as pd
date_data =pd.DataFrame()
date_data.loc[:,'date_5_6']=pd.Series(pd.date_range("2019-5-1", "2019-7-01", freq="15T"))
date_data['all_num'] = 0
#date_data.head(10)

In [10]:
date_data.head(20)

              date_5_6  all_num
0  2019-05-01 00:00:00        0
1  2019-05-01 00:15:00        0
2  2019-05-01 00:30:00        0
3  2019-05-01 00:45:00        0
4  2019-05-01 01:00:00        0
5  2019-05-01 01:15:00        0
6  2019-05-01 01:30:00        0
7  2019-05-01 01:45:00        0
8  2019-05-01 02:00:00        0
9  2019-05-01 02:15:00        0
10 2019-05-01 02:30:00        0
11 2019-05-01 02:45:00        0
12 2019-05-01 03:00:00        0
13 2019-05-01 03:15:00        0
14 2019-05-01 03:30:00        0
15 2019-05-01 03:45:00        0
16 2019-05-01 04:00:00        0
17 2019-05-01 04:15:00        0
18 2019-05-01 04:30:00        0
19 2019-05-01 04:45:00        0

In [11]:
date_data.index

RangeIndex(start=0, stop=5857, step=1)

In [12]:
date_data1 = date_data[0:10,:]
data_ap1 = date_ap[0:100,:]


import sys
for idx, row in date_data1.iterrows():
    for idx1, row1 in data_ap1.iterrows():
        #date_data.loc[(date_data['date_5_6']>row1.START_USING_TIME)&(date_data['date_5_6']<row1.END_USING_TIME)),['all_num']]+=1
        #print(row1.START_USING_TIME,"||",row1.END_USING_TIME)
        #print(row1.START_USING_TIME<row.date_5_6)
        #print(True&True)
        if row.date_5_6>row1.START_USING_TIME and row.date_5_6<row1.END_USING_TIME:
            date_data1.set_value(idx,'all_num',row.all_num+1)   
date_data1.head()

TypeError: '(slice(0, 10, None), slice(None, None, None))' is an invalid key

In [ ]:
import sys
for idx, row in date_data.iterrows():
    for idx1, row1 in data_ap.iterrows():
        #date_data.loc[(date_data['date_5_6']>row1.START_USING_TIME)&(date_data['date_5_6']<row1.END_USING_TIME)),['all_num']]+=1
        #print(row1.START_USING_TIME,"||",row1.END_USING_TIME)
        #print(row1.START_USING_TIME<row.date_5_6)
        #print(True&True)
        if row.date_5_6>row1.START_USING_TIME and row.date_5_6<row1.END_USING_TIME:
            date_data.set_value(idx,'all_num',row.all_num+1)

In [ ]:
date_data.head(20)