In [1]:
import tensorflow as tf
#Data Manipulation
import numpy as np
import pandas as pd

#Visualization
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

#Importing Dependencies
%matplotlib inline

import math

C:\Users\user\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\user\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\user\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\user\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\user\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\user\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

KeyboardInterrupt:

In [ ]:
#파일 불러오기
ap_data = pd.read_csv('LOG_CONCAT_ssy.csv', engine='python', index_col=0)

In [ ]:
ap_data.head(5)

In [4]:
ap_data.info()

<class 'pandas.core.frame.DataFrame'>
Float64Index: 125115 entries, 3.0 to 72799.0
Data columns (total 31 columns):
jnuradacctid            125024 non-null float64
acctsessionid           125020 non-null object
acctuniqueid            125024 non-null object
username                125024 non-null object
groupname               0 non-null float64
realm                   3664 non-null object
nasipaddress            125024 non-null object
nasportid               125024 non-null float64
nasporttype             125024 non-null object
acctstarttime           125024 non-null object
acctstoptime            125024 non-null object
real_time               125024 non-null object
acctsessiontime         125115 non-null int64
acctauthentic           118367 non-null object
connectinfo_start       51343 non-null object
connectinfo_stop        42621 non-null object
acctinputoctets         125024 non-null float64
acctoutputoctets        125024 non-null float64
calledstationid         125024 non-null object
ipaddress               125024 non-null object
place                   124068 non-null object
callingstationid        125024 non-null object
acctterminatecause      107381 non-null object
servicetype             0 non-null float64
framedprotocol          0 non-null float64
framedipaddress         125024 non-null object
acctstartdelay          125024 non-null float64
acctstopdelay           125024 non-null float64
xascendsessionsvrkey    0 non-null float64
server                  125024 non-null object
number                  125115 non-null int64
dtypes: float64(10), int64(2), object(19)
memory usage: 30.5+ MB

In [5]:
ap_data = ap_data.reset_index(drop=True)

In [6]:
ap_data.head(5)

,jnuradacctid,acctsessionid,acctuniqueid,username,groupname,realm,nasipaddress,nasportid,nasporttype,acctstarttime,...,callingstationid,acctterminatecause,servicetype,framedprotocol,framedipaddress,acctstartdelay,acctstopdelay,xascendsessionsvrkey,server,number
0,80667513.0,00002801-00000470,977346d2dd8a9ba2d2eb0a07c9c81541,192777,NaN,NaN,168.131.13.224,0.0,Wireless-802.11,2019-09-20 0:25,...,08-AE-D6-30-A0-33,NaN,NaN,NaN,10.10.12.83,0.0,0.0,NaN,168.131.33.63,0
1,80667663.0,00003001-0000023D,45c4ba1bc250e54cfe82030e9c09ad1a,171594,NaN,NaN,168.131.13.224,0.0,Wireless-802.11,2019-09-20 1:24,...,A8-2B-B9-19-C8-5C,User-Request,NaN,NaN,10.10.1.144,0.0,0.0,NaN,168.131.33.63,1
2,80668351.0,00004001-00000236,d115f6d0b261fc722c5ec9a04823f9f3,193562,NaN,NaN,168.131.13.224,0.0,Wireless-802.11,2019-09-20 0:22,...,C4-93-D9-CE-A7-5D,User-Request,NaN,NaN,168.131.214.29,0.0,0.0,NaN,168.131.33.63,2
3,80675437.0,00021401-000011DC,7bb6ebbfe7ef1f768ace5bbf47c061f1,193562,NaN,NaN,168.131.13.222,0.0,Wireless-802.11,2019-09-20 0:26,...,C4-93-D9-CE-A7-5D,User-Request,NaN,NaN,10.10.40.252,0.0,0.0,NaN,168.131.33.63,3
4,80675438.0,00021401-000011DD,6b69327f47c917102170c73c08032506,142825,NaN,NaN,168.131.13.222,0.0,Wireless-802.11,2019-09-20 0:55,...,64-7B-CE-8D-64-7A,NaN,NaN,NaN,10.10.60.142,0.0,0.0,NaN,168.131.33.63,4

In [7]:
#사용할 칼럼만 추출
ap_data = ap_data[["username","number","place","acctstarttime","acctstoptime",'real_time',"acctsessiontime","calledstationid","ipaddress","callingstationid"]]

In [8]:
ap_data.head(10)

,username,number,place,acctstarttime,acctstoptime,real_time,acctsessiontime,calledstationid,ipaddress,callingstationid
0,192777,0,NaN,2019-09-20 0:25,2019-09-20 0:38,0:12:23,743,F4D9FBE30A20,168.131.184.176,08-AE-D6-30-A0-33
1,171594,1,정보전산원,2019-09-20 1:24,2019-09-20 1:40,0:15:25,925,F4D9FBE30AE0,168.131.184.178,A8-2B-B9-19-C8-5C
2,193562,2,정보전산원,2019-09-20 0:22,2019-09-20 0:39,0:16:16,976,F4D9FBEA1FE0,168.131.184.183,C4-93-D9-CE-A7-5D
3,193562,3,공과대학 5호관,2019-09-20 0:26,2019-09-20 0:48,0:22:28,1348,20DBAB6CB340,168.131.180.138,C4-93-D9-CE-A7-5D
4,142825,4,공과대학 5호관,2019-09-20 0:55,2019-09-20 1:15,0:19:10,1150,20DBAB6CB340,168.131.180.138,64-7B-CE-8D-64-7A
5,174905,5,공과대학 5호관,2019-09-20 0:38,2019-09-20 0:56,0:18:31,1111,F4D9FBDF9000,168.131.180.139,64-C2-DE-73-D5-B5
6,157302,6,공과대학 5호관,2019-09-20 0:49,2019-09-20 1:04,0:15:00,900,F4D9FBDF9000,168.131.180.139,50-77-05-07-27-FD
7,178659,7,공과대학 7호관,2019-09-20 1:15,2019-09-20 1:35,0:19:43,1183,20DBAB7A2140,168.131.180.208,A8-7C-01-F4-0E-6E
8,182638,8,공과대학 2호관,2019-09-20 0:29,2019-09-20 0:50,0:20:45,1245,20DBAB6CAC40,168.131.180.50,50-77-05-6D-82-F1
9,164253,9,공과대학 1호관,2019-09-20 1:00,2019-09-20 1:24,0:24:08,1448,F4D9FBDDF900,168.131.180.21,F8-E6-1A-8A-97-37

In [12]:
ap_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125115 entries, 0 to 125114
Data columns (total 15 columns):
username                125024 non-null object
number                  125115 non-null int64
place                   124068 non-null object
acctstarttime           125024 non-null datetime64[ns]
acctstoptime            125024 non-null datetime64[ns]
real_time               125024 non-null object
acctsessiontime         125115 non-null int64
calledstationid         125024 non-null object
ipaddress               125024 non-null object
callingstationid        125024 non-null object
acctstarttime_year      125024 non-null float64
acctstarttime_month     125024 non-null float64
acctstarttime_day       125024 non-null float64
acctstarttime_hour      125024 non-null float64
acctstarttime_minute    125024 non-null float64
dtypes: datetime64[ns](2), float64(5), int64(2), object(6)
memory usage: 14.3+ MB

In [13]:
ap_data.head(5)

,username,number,place,acctstarttime,acctstoptime,real_time,acctsessiontime,calledstationid,ipaddress,callingstationid,acctstarttime_year,acctstarttime_month,acctstarttime_day,acctstarttime_hour,acctstarttime_minute
0,192777,0,NaN,2019-09-20 00:25:00,2019-09-20 00:38:00,0:12:23,743,F4D9FBE30A20,168.131.184.176,08-AE-D6-30-A0-33,2019.0,9.0,20.0,0.0,25.0
1,171594,1,정보전산원,2019-09-20 01:24:00,2019-09-20 01:40:00,0:15:25,925,F4D9FBE30AE0,168.131.184.178,A8-2B-B9-19-C8-5C,2019.0,9.0,20.0,1.0,24.0
2,193562,2,정보전산원,2019-09-20 00:22:00,2019-09-20 00:39:00,0:16:16,976,F4D9FBEA1FE0,168.131.184.183,C4-93-D9-CE-A7-5D,2019.0,9.0,20.0,0.0,22.0
3,193562,3,공과대학 5호관,2019-09-20 00:26:00,2019-09-20 00:48:00,0:22:28,1348,20DBAB6CB340,168.131.180.138,C4-93-D9-CE-A7-5D,2019.0,9.0,20.0,0.0,26.0
4,142825,4,공과대학 5호관,2019-09-20 00:55:00,2019-09-20 01:15:00,0:19:10,1150,20DBAB6CB340,168.131.180.138,64-7B-CE-8D-64-7A,2019.0,9.0,20.0,0.0,55.0

In [14]:
ap_data.isnull().sum()

username                  91
number                     0
place                   1047
acctstarttime             91
acctstoptime              91
real_time                 91
acctsessiontime            0
calledstationid           91
ipaddress                 91
callingstationid          91
acctstarttime_year        91
acctstarttime_month       91
acctstarttime_day         91
acctstarttime_hour        91
acctstarttime_minute      91
dtype: int64

In [15]:
#null값을 가진 행 모두 제거
ap_data = ap_data.dropna(how = 'any',axis = 0)

In [16]:
ap_data.sort_index(axis = 1)

,acctsessiontime,acctstarttime,acctstarttime_day,acctstarttime_hour,acctstarttime_minute,acctstarttime_month,acctstarttime_year,acctstoptime,calledstationid,callingstationid,ipaddress,number,place,real_time,username
1,925,2019-09-20 01:24:00,20.0,1.0,24.0,9.0,2019.0,2019-09-20 01:40:00,F4D9FBE30AE0,A8-2B-B9-19-C8-5C,168.131.184.178,1,정보전산원,0:15:25,171594
2,976,2019-09-20 00:22:00,20.0,0.0,22.0,9.0,2019.0,2019-09-20 00:39:00,F4D9FBEA1FE0,C4-93-D9-CE-A7-5D,168.131.184.183,2,정보전산원,0:16:16,193562
3,1348,2019-09-20 00:26:00,20.0,0.0,26.0,9.0,2019.0,2019-09-20 00:48:00,20DBAB6CB340,C4-93-D9-CE-A7-5D,168.131.180.138,3,공과대학 5호관,0:22:28,193562
4,1150,2019-09-20 00:55:00,20.0,0.0,55.0,9.0,2019.0,2019-09-20 01:15:00,20DBAB6CB340,64-7B-CE-8D-64-7A,168.131.180.138,4,공과대학 5호관,0:19:10,142825
5,1111,2019-09-20 00:38:00,20.0,0.0,38.0,9.0,2019.0,2019-09-20 00:56:00,F4D9FBDF9000,64-C2-DE-73-D5-B5,168.131.180.139,5,공과대학 5호관,0:18:31,174905
6,900,2019-09-20 00:49:00,20.0,0.0,49.0,9.0,2019.0,2019-09-20 01:04:00,F4D9FBDF9000,50-77-05-07-27-FD,168.131.180.139,6,공과대학 5호관,0:15:00,157302
7,1183,2019-09-20 01:15:00,20.0,1.0,15.0,9.0,2019.0,2019-09-20 01:35:00,20DBAB7A2140,A8-7C-01-F4-0E-6E,168.131.180.208,7,공과대학 7호관,0:19:43,178659
8,1245,2019-09-20 00:29:00,20.0,0.0,29.0,9.0,2019.0,2019-09-20 00:50:00,20DBAB6CAC40,50-77-05-6D-82-F1,168.131.180.50,8,공과대학 2호관,0:20:45,182638
9,1448,2019-09-20 01:00:00,20.0,1.0,0.0,9.0,2019.0,2019-09-20 01:24:00,F4D9FBDDF900,F8-E6-1A-8A-97-37,168.131.180.21,9,공과대학 1호관,0:24:08,164253
10,1346,2019-09-20 01:27:00,20.0,1.0,27.0,9.0,2019.0,2019-09-20 01:50:00,20DBAB6AD140,94-8B-C1-F0-B0-DE,168.131.180.49,10,공과대학 2호관,0:22:26,152425
11,1101,2019-09-20 00:03:00,20.0,0.0,3.0,9.0,2019.0,2019-09-20 00:22:00,20DBAB6CBB40,D4-A3-3D-A0-9B-3D,168.131.181.50,11,진리관,0:18:21,182904
12,1124,2019-09-20 00:35:00,20.0,0.0,35.0,9.0,2019.0,2019-09-20 00:54:00,20DBAB7A2120,08-D4-6A-AF-89-F9,168.131.184.73,12,예술대학 2호관,0:18:44,195592
13,1044,2019-09-20 00:30:00,20.0,0.0,30.0,9.0,2019.0,2019-09-20 00:47:00,20DBAB7A6100,D0-2B-20-80-93-D7,168.131.184.77,13,예술대학 2호관,0:17:24,152336
14,900,2019-09-20 00:34:00,20.0,0.0,34.0,9.0,2019.0,2019-09-20 00:49:00,20DBAB7A6100,88-B2-91-17-A6-5E,168.131.184.77,14,예술대학 2호관,0:15:00,201909509
15,1499,2019-09-20 00:02:00,20.0,0.0,2.0,9.0,2019.0,2019-09-20 00:26:00,20DBAB7A1580,88-AE-07-0B-32-DD,168.131.184.106,15,예술대학 3호관,0:24:59,144210
16,1057,2019-09-20 00:05:00,20.0,0.0,5.0,9.0,2019.0,2019-09-20 00:23:00,20DBAB79E4C0,48-4B-AA-66-3C-46,168.131.184.110,16,예술대학 3호관,0:17:37,193076
17,1255,2019-09-20 00:10:00,20.0,0.0,10.0,9.0,2019.0,2019-09-20 00:31:00,20DBAB7A0180,C4-61-8B-E6-C1-63,168.131.249.210,17,사범대학 4호관,0:20:55,174061
18,1080,2019-09-20 00:20:00,20.0,0.0,20.0,9.0,2019.0,2019-09-20 00:38:00,20DBAB79FEC0,C4-93-D9-CE-A7-5D,168.131.251.37,18,창조관,0:18:00,193562
19,1045,2019-09-20 00:21:00,20.0,0.0,21.0,9.0,2019.0,2019-09-20 00:39:00,20DBAB7A1480,C4-93-D9-CE-A7-5D,168.131.180.237,19,창조관,0:17:25,193562
20,900,2019-09-20 00:21:00,20.0,0.0,21.0,9.0,2019.0,2019-09-20 00:36:00,20DBAB7A1480,C4-93-D9-CE-A7-5D,168.131.180.237,20,창조관,0:15:00,193562
21,1524,2019-09-20 00:49:00,20.0,0.0,49.0,9.0,2019.0,2019-09-20 01:15:00,20DBAB6C8380,F8-E6-1A-8A-97-37,168.131.180.7,21,공과대학 1호관,0:25:24,164253
22,1043,2019-09-20 00:39:00,20.0,0.0,39.0,9.0,2019.0,2019-09-20 00:56:00,F4D9FBDFA600,18-56-80-67-66-6E,168.131.248.227,22,법학전문대학원 2호관,0:17:23,197156
23,900,2019-09-20 01:44:00,20.0,1.0,44.0,9.0,2019.0,2019-09-20 01:59:00,20DBAB6B6900,08-AE-D6-99-1E-EF,168.131.182.66,23,자연과학대학 4호관,0:15:00,167754
24,1072,2019-09-20 00:08:00,20.0,0.0,8.0,9.0,2019.0,2019-09-20 00:26:00,20DBAB6CBFC0,C4-61-8B-E6-A1-B3,168.131.180.8,24,공과대학 1호관,0:17:52,144658
25,1357,2019-09-20 00:08:00,20.0,0.0,8.0,9.0,2019.0,2019-09-20 00:31:00,20DBAB6CBFC0,C4-61-8B-E6-A1-B3,168.131.180.8,25,공과대학 1호관,0:22:37,144658
26,900,2019-09-20 00:30:00,20.0,0.0,30.0,9.0,2019.0,2019-09-20 00:45:00,20DBAB6CC3C0,3C-DC-BC-88-33-A3,168.131.180.58,26,공과대학 2호관,0:15:00,201909463
27,900,2019-09-20 01:27:00,20.0,1.0,27.0,9.0,2019.0,2019-09-20 01:42:00,20DBAB6CC3C0,BC-A5-8B-0A-4C-7E,168.131.180.58,27,공과대학 2호관,0:15:00,154500
28,900,2019-09-20 01:28:00,20.0,1.0,28.0,9.0,2019.0,2019-09-20 01:43:00,20DBAB6CC3C0,50-77-05-DA-4A-02,168.131.180.58,28,공과대학 2호관,0:15:00,158187
29,1050,2019-09-20 00:14:00,20.0,0.0,14.0,9.0,2019.0,2019-09-20 00:32:00,20DBAB79ECA0,70-3C-69-07-D6-6B,168.131.249.101,29,G&R HUB,0:17:30,197294
30,1080,2019-09-20 00:00:00,20.0,0.0,0.0,9.0,2019.0,2019-09-20 00:18:00,20DBAB79F480,80-B0-3D-2C-5B-CC,168.131.249.130,30,G&R HUB,0:18:00,186738
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125085,67,2019-09-24 16:00:00,24.0,16.0,0.0,9.0,2019.0,2019-09-24 16:01:00,34FCB96C1990,B48B1911E672,168.131.181.114,125085,도서관열람실,0:01:07,112633
125086,81,2019-09-24 16:04:00,24.0,16.0,4.0,9.0,2019.0,2019-09-24 16:05:00,34FCB96C1680,B48B1911E672,168.131.181.115,125086,도서관열람실,0:01:21,112633
125087,86,2019-09-24 17:12:00,24.0,17.0,12.0,9.0,2019.0,2019-09-24 17:13:00,34FCB96C1990,B48B1911E672,168.131.181.114,125087,도서관열람실,0:01:26,112633
125088,1220,2019-09-24 17:58:00,24.0,17.0,58.0,9.0,2019.0,2019-09-24 18:18:00,24DEC6B170F0,241B7A49A3D6,168.131.180.3,125088,공과대학 1호관,0:20:20,112692
125089,5467,2019-09-24 08:41:00,24.0,8.0,41.0,9.0,2019.0,2019-09-24 10:12:00,34FCB96AF2E0,041B6DCE11E9,168.131.181.102,125089,도서관별관(백도),1:31:07,112710
125090,56,2019-09-24 12:40:00,24.0,12.0,40.0,9.0,2019.0,2019-09-24 12:41:00,24DEC6A93AB8,E4FAED7A8BB6,168.131.182.229,125090,제1학생회관,0:00:56,112720
125091,367,2019-09-24 12:42:00,24.0,12.0,42.0,9.0,2019.0,2019-09-24 12:49:00,34FCB96AF2E0,E4FAED7A8BB6,168.131.181.102,125091,도서관별관(백도),0:06:07,112720
125092,83,2019-09-24 13:19:00,24.0,13.0,19.0,9.0,2019.0,2019-09-24 13:21:00,34FCB96AF2E0,E4FAED7A8BB6,168.131.181.102,125092,도서관별관(백도),0:01:23,112720
125093,900,2019-09-24 09:55:00,24.0,9.0,55.0,9.0,2019.0,2019-09-24 10:10:00,24DEC6A951E0,58B3FC299FCF,168.131.183.4,125093,수의과대학 1호관,0:15:00,112749
125094,2668,2019-09-24 09:14:00,24.0,9.0,14.0,9.0,2019.0,2019-09-24 09:59:00,24DEC6A94638,3C2EFF6273DE,168.131.180.45,125094,공과대학 2호관,0:44:28,112763
125095,4486,2019-09-24 09:59:00,24.0,9.0,59.0,9.0,2019.0,2019-09-24 11:14:00,24DEC6A94638,3C2EFF6273DE,168.131.180.45,125095,공과대학 2호관,1:14:46,112763
125096,208,2019-09-24 11:18:00,24.0,11.0,18.0,9.0,2019.0,2019-09-24 11:21:00,34FCB96AA300,3C2EFF6273DE,168.131.181.116,125096,도서관열람실,0:03:28,112763
125097,125,2019-09-24 11:24:00,24.0,11.0,24.0,9.0,2019.0,2019-09-24 11:26:00,34FCB96C1990,3C2EFF6273DE,168.131.181.114,125097,도서관열람실,0:02:05,112763
125098,73,2019-09-24 14:05:00,24.0,14.0,5.0,9.0,2019.0,2019-09-24 14:06:00,34FCB96A9080,3C2EFF6273DE,168.131.181.113,125098,도서관열람실,0:01:13,112763
125099,96,2019-09-24 14:24:00,24.0,14.0,24.0,9.0,2019.0,2019-09-24 14:25:00,34FCB96C1690,3C2EFF6273DE,168.131.181.115,125099,도서관열람실,0:01:36,112763
125100,1202,2019-09-24 14:29:00,24.0,14.0,29.0,9.0,2019.0,2019-09-24 14:49:00,6CF37FE0C628,3C2EFF6273DE,168.131.180.102,125100,공과대학 4호관,0:20:02,112763
125101,1570,2019-09-24 09:16:00,24.0,9.0,16.0,9.0,2019.0,2019-09-24 09:43:00,34FCB96C1980,BCB8639FA99B,168.131.181.114,125101,도서관열람실,0:26:10,112763
125102,672,2019-09-24 09:47:00,24.0,9.0,47.0,9.0,2019.0,2019-09-24 09:58:00,34FCB96C1990,BCB8639FA99B,168.131.181.114,125102,도서관열람실,0:11:12,112763
125103,931,2019-09-24 10:05:00,24.0,10.0,5.0,9.0,2019.0,2019-09-24 10:20:00,34FCB96C1990,BCB8639FA99B,168.131.181.114,125103,도서관열람실,0:15:31,112763
125104,1095,2019-09-24 11:22:00,24.0,11.0,22.0,9.0,2019.0,2019-09-24 11:40:00,34FCB96A9080,BCB8639FA99B,168.131.181.113,125104,도서관열람실,0:18:15,112763
125105,1117,2019-09-24 19:40:00,24.0,19.0,40.0,9.0,2019.0,2019-09-24 19:58:00,34FCB96C1990,BCB8639FA99B,168.131.181.114,125105,도서관열람실,0:18:37,112763
125106,949,2019-09-24 20:08:00,24.0,20.0,8.0,9.0,2019.0,2019-09-24 20:23:00,34FCB96C1990,BCB8639FA99B,168.131.181.114,125106,도서관열람실,0:15:49,112763
125107,1033,2019-09-24 20:32:00,24.0,20.0,32.0,9.0,2019.0,2019-09-24 20:49:00,34FCB96C1990,BCB8639FA99B,168.131.181.114,125107,도서관열람실,0:17:13,112763
125108,930,2019-09-24 20:57:00,24.0,20.0,57.0,9.0,2019.0,2019-09-24 21:13:00,34FCB96C1990,BCB8639FA99B,168.131.181.114,125108,도서관열람실,0:15:30,112763
125109,935,2019-09-24 21:21:00,24.0,21.0,21.0,9.0,2019.0,2019-09-24 21:36:00,34FCB96C1990,BCB8639FA99B,168.131.181.114,125109,도서관열람실,0:15:35,112763
125110,215,2019-09-24 22:22:00,24.0,22.0,22.0,9.0,2019.0,2019-09-24 22:26:00,34FCB96C1990,BCB8639FA99B,168.131.181.114,125110,도서관열람실,0:03:35,112763
125111,288,2019-09-24 07:36:00,24.0,7.0,36.0,9.0,2019.0,2019-09-24 07:41:00,34FCB96AF2F0,C81EE7A46B92,168.131.181.102,125111,도서관별관(백도),0:04:48,112771
125112,27,2019-09-24 15:49:00,24.0,15.0,49.0,9.0,2019.0,2019-09-24 15:49:00,34FCB96AF2F0,C81EE7A46B92,168.131.181.102,125112,도서관별관(백도),0:00:27,112771
125113,290,2019-09-24 15:50:00,24.0,15.0,50.0,9.0,2019.0,2019-09-24 15:55:00,34FCB96AF2F0,C81EE7A46B92,168.131.181.102,125113,도서관별관(백도),0:04:50,112771
125114,29,2019-09-24 17:25:00,24.0,17.0,25.0,9.0,2019.0,2019-09-24 17:26:00,34FCB96AF2F0,C81EE7A46B92,168.131.181.102,125114,도서관별관(백도),0:00:29,112771

In [17]:
ap_data.shape

(124068, 15)

In [18]:
ap_data.head(5)

,username,number,place,acctstarttime,acctstoptime,real_time,acctsessiontime,calledstationid,ipaddress,callingstationid,acctstarttime_year,acctstarttime_month,acctstarttime_day,acctstarttime_hour,acctstarttime_minute
1,171594,1,정보전산원,2019-09-20 01:24:00,2019-09-20 01:40:00,0:15:25,925,F4D9FBE30AE0,168.131.184.178,A8-2B-B9-19-C8-5C,2019.0,9.0,20.0,1.0,24.0
2,193562,2,정보전산원,2019-09-20 00:22:00,2019-09-20 00:39:00,0:16:16,976,F4D9FBEA1FE0,168.131.184.183,C4-93-D9-CE-A7-5D,2019.0,9.0,20.0,0.0,22.0
3,193562,3,공과대학 5호관,2019-09-20 00:26:00,2019-09-20 00:48:00,0:22:28,1348,20DBAB6CB340,168.131.180.138,C4-93-D9-CE-A7-5D,2019.0,9.0,20.0,0.0,26.0
4,142825,4,공과대학 5호관,2019-09-20 00:55:00,2019-09-20 01:15:00,0:19:10,1150,20DBAB6CB340,168.131.180.138,64-7B-CE-8D-64-7A,2019.0,9.0,20.0,0.0,55.0
5,174905,5,공과대학 5호관,2019-09-20 00:38:00,2019-09-20 00:56:00,0:18:31,1111,F4D9FBDF9000,168.131.180.139,64-C2-DE-73-D5-B5,2019.0,9.0,20.0,0.0,38.0

In [19]:
# ap_data.describe()

In [20]:
# date_data =pd.DataFrame()
# date_data.loc[:,'date']=pd.Series(pd.date_range("2019-9-20 00:00", "2019-9-25 00:00", freq="H"))
# date_data['all_num']=0

# date_data['datetime'] = pd.to_datetime(date_data['date'])
# date_data = date_data.set_index("datetime")
# date_data.head(20)

In [21]:
date_data =pd.DataFrame()
date_data.loc[:,'date']=pd.Series(pd.date_range("2019-9-20", "2019-9-25", freq="60T"))

#여기서 00:00:00의 all_num의 의미는 0-5분까지의 사람 숫자로 계산할 것이다.
date_data['all_num']=0
date_data.info()
# date_data.head(20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121 entries, 0 to 120
Data columns (total 2 columns):
date       121 non-null datetime64[ns]
all_num    121 non-null int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 2.0 KB

In [22]:
date_data.head(5)

                 date  all_num
0 2019-09-20 00:00:00        0
1 2019-09-20 01:00:00        0
2 2019-09-20 02:00:00        0
3 2019-09-20 03:00:00        0
4 2019-09-20 04:00:00        0

In [23]:
# date_data.iloc[:,0]

In [24]:
class Queue:
    queue = []
    
    def __init__(self):
        self.queue = [] 
 
    def push(self, num):
        if self.size() == 10:
            self.pop()
        self.queue.append(num)
        
 
    def pop(self):
        return self.queue.pop(0) if len(self.queue) != 0 else -1
 
    def size(self):
        return len(self.queue)
 
    def empty(self):
        return 1 if self.size() == 0 else 0
 
    def front(self):
        return self.queue[0] if self.size() != 0 else -1
 
    def back(self):
        return self.queue[-1] if self.size() != 0 else -1

In [25]:
 
#몇개의 숫자를 받을건지

queue = Queue()
queue.push(1)
queue.push(2)
queue.push(3)
queue.push(4)
queue.push(5)
queue.push(6)
queue.push(7)
queue.push(8)
queue.push(9)
queue.push(10)
queue.push(11)
queue.push(12)
queue.pop()
queue.pop()
queue.pop()

# count = list_duplicates_of(queue,7)
# print(count)
print(queue.queue)

[6, 7, 8, 9, 10, 11, 12]

In [26]:
# 중복 인덱스 값 추출

def list_duplicates_of(seq,item):
    start_at = -1
    locs = []
    while True:
        try:
            loc = seq.index(item,start_at+1)
        except ValueError:
            break
        else:
            locs.append(loc)
            start_at = loc
    return locs

In [27]:
list = [7]
value =list[0]

In [28]:
list_duplicates_of(queue.queue,list[0])

[1]

In [29]:
queue.queue[1]

7

In [30]:
ap_data = ap_data.loc[(ap_data['calledstationid']=='34FCB96AF2F0'),:]

In [31]:
ap_data['username'].value_counts()

112771      40
165265      34
150166      33
190226      28
65716       28
            ..
194248       1
140356       1
148826       1
92646        1
brendan2     1
Name: username, Length: 536, dtype: int64

In [32]:
ap_data = ap_data.sort_values(by = 'acctstarttime', ascending = True)

In [33]:
ap_data.head(20)

,username,number,place,acctstarttime,acctstoptime,real_time,acctsessiontime,calledstationid,ipaddress,callingstationid,acctstarttime_year,acctstarttime_month,acctstarttime_day,acctstarttime_hour,acctstarttime_minute
39457,176272,39457,도서관별관(백도),2019-09-20 07:32:00,2019-09-20 07:34:00,0:01:36,96,34FCB96AF2F0,168.131.181.102,9CE6E7CDDA56,2019.0,9.0,20.0,7.0,32.0
17997,176272,17997,도서관별관(백도),2019-09-20 07:32:00,2019-09-20 07:34:00,0:01:36,96,34FCB96AF2F0,168.131.181.102,9CE6E7CDDA56,2019.0,9.0,20.0,7.0,32.0
33702,120286,33702,도서관별관(백도),2019-09-20 08:09:00,2019-09-20 08:12:00,0:03:26,206,34FCB96AF2F0,168.131.181.102,D02B20B276E4,2019.0,9.0,20.0,8.0,9.0
9994,120286,9994,도서관별관(백도),2019-09-20 08:09:00,2019-09-20 08:12:00,0:03:26,206,34FCB96AF2F0,168.131.181.102,D02B20B276E4,2019.0,9.0,20.0,8.0,9.0
33824,120815,33824,도서관별관(백도),2019-09-20 08:11:00,2019-09-20 08:12:00,0:00:47,47,34FCB96AF2F0,168.131.181.102,FC183C4C9280,2019.0,9.0,20.0,8.0,11.0
10066,120815,10066,도서관별관(백도),2019-09-20 08:11:00,2019-09-20 08:12:00,0:00:47,47,34FCB96AF2F0,168.131.181.102,FC183C4C9280,2019.0,9.0,20.0,8.0,11.0
32678,131528,32678,도서관별관(백도),2019-09-20 08:11:00,2019-09-20 08:12:00,0:00:47,47,34FCB96AF2F0,168.131.181.102,749EAF17113F,2019.0,9.0,20.0,8.0,11.0
12130,131528,12130,도서관별관(백도),2019-09-20 08:11:00,2019-09-20 08:12:00,0:00:47,47,34FCB96AF2F0,168.131.181.102,749EAF17113F,2019.0,9.0,20.0,8.0,11.0
10968,150638,10968,도서관별관(백도),2019-09-20 08:26:00,2019-09-20 08:27:00,0:00:35,35,34FCB96AF2F0,168.131.181.102,18F643292270,2019.0,9.0,20.0,8.0,26.0
36106,150638,36106,도서관별관(백도),2019-09-20 08:26:00,2019-09-20 08:27:00,0:00:35,35,34FCB96AF2F0,168.131.181.102,18F643292270,2019.0,9.0,20.0,8.0,26.0
10969,150638,10969,도서관별관(백도),2019-09-20 08:27:00,2019-09-20 08:29:00,0:02:17,137,34FCB96AF2F0,168.131.181.102,18F643292270,2019.0,9.0,20.0,8.0,27.0
36107,150638,36107,도서관별관(백도),2019-09-20 08:27:00,2019-09-20 08:29:00,0:02:17,137,34FCB96AF2F0,168.131.181.102,18F643292270,2019.0,9.0,20.0,8.0,27.0
9288,112771,9288,도서관별관(백도),2019-09-20 08:30:00,2019-09-20 08:32:00,0:01:31,91,34FCB96AF2F0,168.131.181.102,C81EE7A46B92,2019.0,9.0,20.0,8.0,30.0
32734,112771,32734,도서관별관(백도),2019-09-20 08:30:00,2019-09-20 08:32:00,0:01:31,91,34FCB96AF2F0,168.131.181.102,C81EE7A46B92,2019.0,9.0,20.0,8.0,30.0
33493,133015,33493,도서관별관(백도),2019-09-20 08:33:00,2019-09-20 08:40:00,0:07:06,426,34FCB96AF2F0,168.131.181.102,F8E94EA2C5D3,2019.0,9.0,20.0,8.0,33.0
12678,133015,12678,도서관별관(백도),2019-09-20 08:33:00,2019-09-20 08:40:00,0:07:06,426,34FCB96AF2F0,168.131.181.102,F8E94EA2C5D3,2019.0,9.0,20.0,8.0,33.0
38744,161360,38744,도서관별관(백도),2019-09-20 08:39:00,2019-09-20 08:44:00,0:05:11,311,34FCB96AF2F0,168.131.181.102,08AED644F8DB,2019.0,9.0,20.0,8.0,39.0
34054,133575,34054,도서관별관(백도),2019-09-20 08:39:00,2019-09-20 08:40:00,0:00:47,47,34FCB96AF2F0,168.131.181.102,D868C36D1DD1,2019.0,9.0,20.0,8.0,39.0
10906,161360,10906,도서관별관(백도),2019-09-20 08:39:00,2019-09-20 08:44:00,0:05:11,311,34FCB96AF2F0,168.131.181.102,08AED644F8DB,2019.0,9.0,20.0,8.0,39.0
13115,133575,13115,도서관별관(백도),2019-09-20 08:39:00,2019-09-20 08:40:00,0:00:47,47,34FCB96AF2F0,168.131.181.102,D868C36D1DD1,2019.0,9.0,20.0,8.0,39.0

In [34]:
# ap_data.set_index(ap_data['acctstarttime'], inplace = True)

In [35]:
# ap_data.head(5)

In [36]:
# 중복값 제거 (큐 이용)

queue1 = Queue()  #username 0
queue2 = Queue()  #acctstarttime  3
queue3 = Queue() #acctsessiontime   6
queue4 = Queue()  #index  1

minn = 0

for idx1, row1 in date_data.iterrows():
    queue1.queue = [] 
    queue2.queue = [] 
    queue3.queue = [] 
    queue4.queue = []
    print(" ")
    print(" ")
    print(" ")
    print("date_data : ", row1.date)
    for idx, row in ap_data.iterrows(): 
        print("idx : ", idx)
        timestamp = row.acctstarttime
        print("timestamp : ", timestamp)
        if row1.date.hour + 1 < row.acctstarttime.hour:
            break
            
        while(date_data.iat[idx1,0] < timestamp) and (timestamp < date_data.iat[idx1+1,0]):
            list = queue1.queue
            print("list : ", list)
#             coll = ap_data.iat[idx-1,1]
#             print("coll : ", coll)
#             print("username : ", ap_data.iloc[coll,])
#             print("username : ", ap_data.iat[idx-1,0])
            if ap_data.iat[idx-1,0] in list :
                print("중복!!")
                list1 = list_duplicates_of(queue1.queue, ap_data.iat[idx-1,0])
                print("list1 : ", list1)
                
                if ap_data.iat[idx,6] < queue3.queue[list1[0]]:
                    minn = ap_data.iat[idx-1,1]
                else:
                    minn = queue4.queue[list1[0]] 
                    
                #ap_data = ap_data[ap_data.number != minn]
                break
    
            print("헤이")
            queue1.push(ap_data.iat[idx-1,0])
            print("queue1 : ",queue1.queue)
            queue2.push(ap_data.iat[idx-1,3])
            print("queue2 : ",queue2.queue)
            queue3.push(ap_data.iat[idx-1,6])
            print("queue3 : ",queue3.queue)
            queue4.push(ap_data.iat[idx-1,1]) 
            print("queue4 : ",queue4.queue)
            break

date_data :  2019-09-20 00:00:00
idx :  39457
timestamp :  2019-09-20 07:32:00



date_data :  2019-09-20 01:00:00
idx :  39457
timestamp :  2019-09-20 07:32:00



date_data :  2019-09-20 02:00:00
idx :  39457
timestamp :  2019-09-20 07:32:00



date_data :  2019-09-20 03:00:00
idx :  39457
timestamp :  2019-09-20 07:32:00



date_data :  2019-09-20 04:00:00
idx :  39457
timestamp :  2019-09-20 07:32:00



date_data :  2019-09-20 05:00:00
idx :  39457
timestamp :  2019-09-20 07:32:00



date_data :  2019-09-20 06:00:00
idx :  39457
timestamp :  2019-09-20 07:32:00
idx :  17997
timestamp :  2019-09-20 07:32:00
idx :  33702
timestamp :  2019-09-20 08:09:00



date_data :  2019-09-20 07:00:00
idx :  39457
timestamp :  2019-09-20 07:32:00
list :  []

IndexError: index 39456 is out of bounds for axis 0 with size 1824

In [ ]:
# # 중복값 제거 (큐 이용)

# queue1 = Queue()  #username 0
# queue2 = Queue()  #acctstarttime  3
# queue3 = Queue() #acctsessiontime   6
# queue4 = Queue()  #index  1

# minn = 0

# for idx1, row1 in date_data.iterrows():
#     queue1.queue = [] 
#     queue2.queue = [] 
#     queue3.queue = [] 
#     queue4.queue = []
#     print("date_data : ", row1.date)
    
#     for idx, row in ap_data.iterrows(): 
#         print("idx : ", idx)
#         timestamp = row.acctstarttime
#         print("timestamp : ", timestamp)
        
#         while(date_data.iat[idx1,0] < timestamp) and (timestamp < date_data.iat[idx1+1,0]):
#             list = queue1.queue
#             print("list : ", list)
#             print("username : ", ap_data.iat[idx-1,0])
            
#             if ap_data.iat[idx-1,0] == 'nan':
#                 break
            
#             if ap_data.iat[idx-1,0] in list :
#                 print("중복!!")
#                 list1 = list_duplicates_of(queue1.queue, ap_data.iat[idx-1,0])
#                 print("list1 : ", list1)
                
#                 if ap_data.iat[idx,6] < queue3.queue[list1[0]]:
#                     minn = ap_data.iat[idx-1,1]
#                 else:
#                     minn = queue4.queue[list1[0]] 
                    
#                 ap_data[[ap_data['number'] == minn],:] = np.nan
#                 #ap_data = ap_data[ap_data.number != minn]
#                 break
      
#             print("헤이")
#             queue1.push(ap_data.iat[idx-1,0])
#             print("queue1 : ",queue1.queue)
#             queue2.push(ap_data.iat[idx-1,3])
#             print("queue2 : ",queue2.queue)
#             queue3.push(ap_data.iat[idx-1,6])
#             print("queue3 : ",queue3.queue)
#             queue4.push(ap_data.iat[idx-1,1]) 
#             print("queue4 : ",queue4.queue)
#             break

                
#             print("헤이")   
#             queue1.push(ap_data.iloc[idx,0])
#             print("queue1 : ",queue1.queue)
#             queue2.push(ap_data.iloc[idx,3])
#             print("queue2 : ",queue2.queue)
#             queue3.push(ap_data.iloc[idx,6])
#             print("queue3 : ",queue3.queue)
#             queue4.push(ap_data.iloc[idx,1]) 
#             print("queue4 : ",queue4.queue)
#             break

In [9]:
ap_data['acctstoptime'] =  pd.to_datetime(ap_data['acctstoptime'], infer_datetime_format=True)

In [ ]:
ap_data['acctstarttime'] =  pd.to_datetime(ap_data['acctstarttime'], infer_datetime_format=True)

In [ ]:
ap_data['acctstarttime_year'] = ap_data['acctstarttime'].dt.year
ap_data['acctstarttime_month'] = ap_data['acctstarttime'].dt.month
ap_data['acctstarttime_day'] = ap_data['acctstarttime'].dt.day
ap_data['acctstarttime_hour'] = ap_data['acctstarttime'].dt.hour
ap_data['acctstarttime_minute'] = ap_data['acctstarttime'].dt.minute

In [ ]:
# # 중복값 제거 (큐 이용)

# queue1 = Queue()  #username 0
# queue2 = Queue()  #acctstarttime  3
# queue3 = Queue() #acctsessiontime   6
# queue4 = Queue()  #index  1

# minn = 0

# for idx1, row1 in date_data.iterrows():
#     queue1.queue = [] 
#     queue2.queue = [] 
#     queue3.queue = [] 
#     queue4.queue = []
#     print("date_data : ", row1.date)
    
#     for idx, row in ap_data.iterrows(): 
#         print("idx : ", idx)
#         timestamp = row.acctstarttime
#         print("timestamp : ", timestamp)
        
#         while(date_data.iat[idx1,0] < timestamp) and (timestamp < date_data.iat[idx1+1,0]):
#             list = queue1.queue
#             print("list : ", list)
#             print("username : ", ap_data.iat[idx-1,0])
#             if ap_data.iat[idx-1,0] in list :
#                 print("중복!!")
#                 list1 = list_duplicates_of(queue1.queue, ap_data.iat[idx-1,0])
#                 print("list1 : ", list1)
                
#                 if ap_data.iat[idx,6] < queue3.queue[list1[0]]:
#                     minn = ap_data.iat[idx-1,1]
#                 else:
#                     minn = queue4.queue[list1[0]] 
                    
#                 #ap_data = ap_data[ap_data.number != minn]
#                 break
    
#             print("헤이")
#             queue1.push(ap_data.iat[idx-1,0])
#             print("queue1 : ",queue1.queue)
#             queue2.push(ap_data.iat[idx-1,3])
#             print("queue2 : ",queue2.queue)
#             queue3.push(ap_data.iat[idx-1,6])
#             print("queue3 : ",queue3.queue)
#             queue4.push(ap_data.iat[idx-1,1]) 
#             print("queue4 : ",queue4.queue)
#             break