In [1]:
import pandas as pd
import numpy as np

In [2]:
ap_data = pd.read_excel("exact_data1.xlsx")

In [3]:
ap_data.head(-1)

,Unnamed: 0,username,place,acctstarttime,acctstoptime,acctsessiontime,calledstationid,ipaddress,callingstationid,acctstarttime_year,acctstarttime_month,acctstarttime_day,acctstarttime_hour,acctstarttime_minute
0,0,NaN,도서관열람실,2019-09-20 00:00:00,2019-09-20 00:01:00,40.0,34FCB96C1690,168.131.181.115,9CE65E074BB4,2019,9,20,0,0
1,1,NaN,도서관열람실,2019-09-20 00:00:00,2019-09-20 00:01:00,40.0,34FCB96C1690,168.131.181.115,9CE65E074BB4,2019,9,20,0,0
2,2,163671,도서관열람실,2019-09-20 00:00:00,2019-09-20 00:01:00,40.0,34FCB96C1690,168.131.181.115,9CE65E074BB4,2019,9,20,0,0
3,3,NaN,도서관열람실,2019-09-20 00:02:00,2019-09-20 00:03:00,23.0,34FCB96C1690,168.131.181.115,B4F7A1C2F002,2019,9,20,0,2
4,4,NaN,도서관열람실,2019-09-20 00:02:00,2019-09-20 00:03:00,23.0,34FCB96C1690,168.131.181.115,B4F7A1C2F002,2019,9,20,0,2
5,5,161737,도서관열람실,2019-09-20 00:02:00,2019-09-20 00:03:00,23.0,34FCB96C1690,168.131.181.115,B4F7A1C2F002,2019,9,20,0,2
6,6,NaN,도서관열람실,2019-09-20 00:03:00,2019-09-20 00:04:00,99.0,34FCB96C1680,168.131.181.115,BCE63F1E4F96,2019,9,20,0,3
7,7,NaN,도서관열람실,2019-09-20 00:03:00,2019-09-20 00:04:00,99.0,34FCB96C1680,168.131.181.115,BCE63F1E4F96,2019,9,20,0,3
8,8,123111,도서관열람실,2019-09-20 00:03:00,2019-09-20 00:04:00,99.0,34FCB96C1680,168.131.181.115,BCE63F1E4F96,2019,9,20,0,3
9,9,NaN,도서관열람실,2019-09-20 00:06:00,2019-09-20 00:07:00,37.0,34FCB96C1690,168.131.181.115,60F4456A8F8E,2019,9,20,0,6
10,10,NaN,도서관열람실,2019-09-20 00:06:00,2019-09-20 00:07:00,37.0,34FCB96C1690,168.131.181.115,60F4456A8F8E,2019,9,20,0,6
11,11,62862,도서관열람실,2019-09-20 00:06:00,2019-09-20 00:07:00,37.0,34FCB96C1690,168.131.181.115,60F4456A8F8E,2019,9,20,0,6
12,12,NaN,도서관열람실,2019-09-20 00:06:00,2019-09-20 00:07:00,46.0,34FCB96C1680,168.131.181.115,D0B12866743B,2019,9,20,0,6
13,13,NaN,도서관열람실,2019-09-20 00:06:00,2019-09-20 00:07:00,46.0,34FCB96C1680,168.131.181.115,D0B12866743B,2019,9,20,0,6
14,14,165605,도서관열람실,2019-09-20 00:06:00,2019-09-20 00:07:00,46.0,34FCB96C1680,168.131.181.115,D0B12866743B,2019,9,20,0,6
15,15,NaN,도서관열람실,2019-09-20 00:10:00,2019-09-20 00:12:00,126.0,34FCB96C1680,168.131.181.115,14205E224242,2019,9,20,0,10
16,16,NaN,도서관열람실,2019-09-20 00:10:00,2019-09-20 00:12:00,126.0,34FCB96C1680,168.131.181.115,14205E224242,2019,9,20,0,10
17,17,141045,도서관열람실,2019-09-20 00:10:00,2019-09-20 00:12:00,126.0,34FCB96C1680,168.131.181.115,14205E224242,2019,9,20,0,10
18,18,NaN,도서관열람실,2019-09-20 00:10:00,2019-09-20 00:11:00,64.0,34FCB96C1C10,168.131.181.117,886B6E27E0B5,2019,9,20,0,10
19,19,NaN,도서관열람실,2019-09-20 00:10:00,2019-09-20 00:11:00,64.0,34FCB96C1C10,168.131.181.117,886B6E27E0B5,2019,9,20,0,10
20,20,151782,도서관열람실,2019-09-20 00:10:00,2019-09-20 00:11:00,64.0,34FCB96C1C10,168.131.181.117,886B6E27E0B5,2019,9,20,0,10
21,21,200011203,도서관열람실,2019-09-20 06:33:00,2019-09-20 06:35:00,78.0,34FCB96C1680,168.131.181.115,08EE8B24A01F,2019,9,20,6,33
22,22,200011203,도서관열람실,2019-09-20 06:33:00,2019-09-20 06:35:00,78.0,34FCB96C1680,168.131.181.115,08EE8B24A01F,2019,9,20,6,33
23,23,NaN,도서관열람실,2019-09-20 06:57:00,2019-09-20 07:09:00,738.0,34FCB96C1690,168.131.181.115,484BAA4F261C,2019,9,20,6,57
24,24,110763,도서관열람실,2019-09-20 06:57:00,2019-09-20 07:09:00,738.0,34FCB96C1690,168.131.181.115,484BAA4F261C,2019,9,20,6,57
25,25,130012,도서관열람실,2019-09-20 07:11:00,2019-09-20 07:11:00,35.0,34FCB96C1690,168.131.181.115,E42B342B9303,2019,9,20,7,11
26,26,130012,도서관열람실,2019-09-20 07:11:00,2019-09-20 07:11:00,35.0,34FCB96C1690,168.131.181.115,E42B342B9303,2019,9,20,7,11
27,27,NaN,도서관열람실,2019-09-20 07:11:00,2019-09-20 07:11:00,10.0,34FCB96C1680,168.131.181.115,F0DBF80C0140,2019,9,20,7,11
28,28,198917,도서관열람실,2019-09-20 07:11:00,2019-09-20 07:11:00,10.0,34FCB96C1680,168.131.181.115,F0DBF80C0140,2019,9,20,7,11
29,29,NaN,도서관열람실,2019-09-20 07:15:00,2019-09-20 07:16:00,86.0,34FCB96C1680,168.131.181.115,D0B128C52C59,2019,9,20,7,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24342,24342,142648,도서관열람실,2019-10-17 23:14:00,2019-10-18 00:01:00,2860.0,34FCB96C1C10,168.131.181.117,A82BB9FE25BB,2019,10,17,23,14
24343,24343,121725,도서관열람실,2019-10-17 23:19:00,2019-10-17 23:29:00,605.0,34FCB96C1690,168.131.181.115,D4909C7C516B,2019,10,17,23,19
24344,24344,104867,도서관열람실,2019-10-17 23:20:00,2019-10-17 23:22:00,133.0,34FCB96C1690,168.131.181.115,C8FF2836A60F,2019,10,17,23,20
24345,24345,191694,도서관열람실,2019-10-17 23:20:00,2019-10-17 23:21:00,50.0,34FCB96C1690,168.131.181.115,F895EA3B5A44,2019,10,17,23,20
24346,24346,164737,도서관열람실,2019-10-17 23:21:00,2019-10-17 23:22:00,60.0,34FCB96C1690,168.131.181.115,FC183CA10FEF,2019,10,17,23,21
24347,24347,160435,도서관열람실,2019-10-17 23:23:00,2019-10-17 23:24:00,33.0,34FCB96C1690,168.131.181.115,E4B2FB4BD24A,2019,10,17,23,23
24348,24348,164765,도서관열람실,2019-10-17 23:24:00,2019-10-17 23:25:00,71.0,34FCB96C1680,168.131.181.115,08EE8B2D77C1,2019,10,17,23,24
24349,24349,163955,도서관열람실,2019-10-17 23:28:00,2019-10-17 23:31:00,191.0,34FCB96C1690,168.131.181.115,D81C79E3C7DD,2019,10,17,23,28
24350,24350,123685,도서관열람실,2019-10-17 23:29:00,2019-10-17 23:32:00,197.0,34FCB96C1680,168.131.181.115,9476B714CB7D,2019,10,17,23,29
24351,24351,191853,도서관열람실,2019-10-17 23:30:00,2019-10-17 23:31:00,91.0,34FCB96C1690,168.131.181.115,08AED6F8BB75,2019,10,17,23,30
24352,24352,181337,도서관열람실,2019-10-17 23:32:00,2019-10-17 23:32:00,32.0,34FCB96C1690,168.131.181.115,4C6BE89B6FEA,2019,10,17,23,32
24353,24353,141055,도서관열람실,2019-10-17 23:37:00,2019-10-17 23:38:00,47.0,34FCB96C1690,168.131.181.115,58404EDB7334,2019,10,17,23,37
24354,24354,145851,도서관열람실,2019-10-17 23:38:00,2019-10-17 23:56:00,1070.0,34FCB96C1680,168.131.181.115,9810E85C1849,2019,10,17,23,38
24355,24355,164753,도서관열람실,2019-10-17 23:39:00,2019-10-17 23:43:00,189.0,34FCB96C1680,168.131.181.115,64C2DE514B76,2019,10,17,23,39
24356,24356,141055,도서관열람실,2019-10-17 23:39:00,2019-10-17 23:43:00,201.0,34FCB96C1690,168.131.181.115,58404EDB7334,2019,10,17,23,39
24357,24357,182280,도서관열람실,2019-10-17 23:41:00,2019-10-17 23:42:00,40.0,34FCB96C1690,168.131.181.115,C0B6580F39C7,2019,10,17,23,41
24358,24358,193333,도서관열람실,2019-10-17 23:42:00,2019-10-17 23:44:00,103.0,34FCB96C1C10,168.131.181.117,74B587AEC6AE,2019,10,17,23,42
24359,24359,102745,도서관열람실,2019-10-17 23:45:00,2019-10-17 23:47:00,68.0,34FCB96C1680,168.131.181.115,74C63B72DD77,2019,10,17,23,45
24360,24360,74264,도서관열람실,2019-10-17 23:49:00,2019-10-18 00:06:00,996.0,34FCB96C1C10,168.131.181.117,A0D7957ED76E,2019,10,17,23,49
24361,24361,163048,도서관열람실,2019-10-17 23:50:00,2019-10-17 23:54:00,224.0,34FCB96C1690,168.131.181.115,F01898CBFE01,2019,10,17,23,50
24362,24362,173050,도서관열람실,2019-10-17 23:50:00,2019-10-17 23:51:00,34.0,34FCB96C1690,168.131.181.115,549963BC0538,2019,10,17,23,50
24363,24363,160081,도서관열람실,2019-10-17 23:51:00,2019-10-17 23:54:00,182.0,34FCB96C1C00,168.131.181.117,80B03D5DD82C,2019,10,17,23,51
24364,24364,162641,도서관열람실,2019-10-17 23:51:00,2019-10-17 23:52:00,51.0,34FCB96C1680,168.131.181.115,5499635E3377,2019,10,17,23,51
24365,24365,162965,도서관열람실,2019-10-17 23:51:00,2019-10-17 23:52:00,34.0,34FCB96C1680,168.131.181.115,A82BB9C83A94,2019,10,17,23,51
24366,24366,171864,도서관열람실,2019-10-17 23:52:00,2019-10-17 23:55:00,192.0,34FCB96C1690,168.131.181.115,80B03DBCE721,2019,10,17,23,52
24367,24367,145531,도서관열람실,2019-10-17 23:53:00,2019-10-17 23:59:00,310.0,34FCB96C1680,168.131.181.115,7C0191CAEB2F,2019,10,17,23,53
24368,24368,145531,도서관열람실,2019-10-17 23:54:00,2019-10-17 23:55:00,61.0,34FCB96C1680,168.131.181.115,F884F2BBB9E1,2019,10,17,23,54
24369,24369,184576,도서관열람실,2019-10-17 23:57:00,2019-10-18 00:00:00,134.0,34FCB96C1680,168.131.181.115,948BC14E5498,2019,10,17,23,57
24370,24370,184576,도서관열람실,2019-10-17 23:58:00,2019-10-17 23:58:00,44.0,34FCB96C1690,168.131.181.115,34A8EBCA37AC,2019,10,17,23,58
24371,24371,120148,도서관열람실,2019-10-17 23:58:00,2019-10-17 23:59:00,56.0,34FCB96C1680,168.131.181.115,F0EE1044E8AE,2019,10,17,23,58

In [4]:
ap_data = ap_data.loc[ap_data['username'].notnull(),:]

In [5]:
ap_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23194 entries, 2 to 24372
Data columns (total 14 columns):
Unnamed: 0              23194 non-null int64
username                23194 non-null object
place                   23194 non-null object
acctstarttime           23194 non-null datetime64[ns]
acctstoptime            23194 non-null datetime64[ns]
acctsessiontime         23194 non-null float64
calledstationid         23194 non-null object
ipaddress               23194 non-null object
callingstationid        23194 non-null object
acctstarttime_year      23194 non-null int64
acctstarttime_month     23194 non-null int64
acctstarttime_day       23194 non-null int64
acctstarttime_hour      23194 non-null int64
acctstarttime_minute    23194 non-null int64
dtypes: datetime64[ns](2), float64(1), int64(6), object(5)
memory usage: 2.7+ MB

In [6]:
ap_data.head()

,Unnamed: 0,username,place,acctstarttime,acctstoptime,acctsessiontime,calledstationid,ipaddress,callingstationid,acctstarttime_year,acctstarttime_month,acctstarttime_day,acctstarttime_hour,acctstarttime_minute
2,2,163671,도서관열람실,2019-09-20 00:00:00,2019-09-20 00:01:00,40.0,34FCB96C1690,168.131.181.115,9CE65E074BB4,2019,9,20,0,0
5,5,161737,도서관열람실,2019-09-20 00:02:00,2019-09-20 00:03:00,23.0,34FCB96C1690,168.131.181.115,B4F7A1C2F002,2019,9,20,0,2
8,8,123111,도서관열람실,2019-09-20 00:03:00,2019-09-20 00:04:00,99.0,34FCB96C1680,168.131.181.115,BCE63F1E4F96,2019,9,20,0,3
11,11,62862,도서관열람실,2019-09-20 00:06:00,2019-09-20 00:07:00,37.0,34FCB96C1690,168.131.181.115,60F4456A8F8E,2019,9,20,0,6
14,14,165605,도서관열람실,2019-09-20 00:06:00,2019-09-20 00:07:00,46.0,34FCB96C1680,168.131.181.115,D0B12866743B,2019,9,20,0,6

In [7]:
ap_data = ap_data.reset_index(drop=True)

In [8]:
ap_data = ap_data.drop('Unnamed: 0', axis = 1)

In [9]:
ap_data.head()

,username,place,acctstarttime,acctstoptime,acctsessiontime,calledstationid,ipaddress,callingstationid,acctstarttime_year,acctstarttime_month,acctstarttime_day,acctstarttime_hour,acctstarttime_minute
0,163671,도서관열람실,2019-09-20 00:00:00,2019-09-20 00:01:00,40.0,34FCB96C1690,168.131.181.115,9CE65E074BB4,2019,9,20,0,0
1,161737,도서관열람실,2019-09-20 00:02:00,2019-09-20 00:03:00,23.0,34FCB96C1690,168.131.181.115,B4F7A1C2F002,2019,9,20,0,2
2,123111,도서관열람실,2019-09-20 00:03:00,2019-09-20 00:04:00,99.0,34FCB96C1680,168.131.181.115,BCE63F1E4F96,2019,9,20,0,3
3,62862,도서관열람실,2019-09-20 00:06:00,2019-09-20 00:07:00,37.0,34FCB96C1690,168.131.181.115,60F4456A8F8E,2019,9,20,0,6
4,165605,도서관열람실,2019-09-20 00:06:00,2019-09-20 00:07:00,46.0,34FCB96C1680,168.131.181.115,D0B12866743B,2019,9,20,0,6

In [10]:
#7열이라고 예상되는 것만 뽑음

# ap_data = ap_data.loc[((ap_data['calledstationid'] == '34FCB96C1C10') | (ap_data['calledstationid'] == '34FCB96C1C00')), :]

In [11]:
#3열
ap_data = ap_data.loc[((ap_data['ipaddress'] == '168.131.181.115')), :]

In [12]:
ap_data = ap_data.reset_index(drop=True)

In [13]:
ap_data.head(-1)

,username,place,acctstarttime,acctstoptime,acctsessiontime,calledstationid,ipaddress,callingstationid,acctstarttime_year,acctstarttime_month,acctstarttime_day,acctstarttime_hour,acctstarttime_minute
0,163671,도서관열람실,2019-09-20 00:00:00,2019-09-20 00:01:00,40.0,34FCB96C1690,168.131.181.115,9CE65E074BB4,2019,9,20,0,0
1,161737,도서관열람실,2019-09-20 00:02:00,2019-09-20 00:03:00,23.0,34FCB96C1690,168.131.181.115,B4F7A1C2F002,2019,9,20,0,2
2,123111,도서관열람실,2019-09-20 00:03:00,2019-09-20 00:04:00,99.0,34FCB96C1680,168.131.181.115,BCE63F1E4F96,2019,9,20,0,3
3,62862,도서관열람실,2019-09-20 00:06:00,2019-09-20 00:07:00,37.0,34FCB96C1690,168.131.181.115,60F4456A8F8E,2019,9,20,0,6
4,165605,도서관열람실,2019-09-20 00:06:00,2019-09-20 00:07:00,46.0,34FCB96C1680,168.131.181.115,D0B12866743B,2019,9,20,0,6
5,141045,도서관열람실,2019-09-20 00:10:00,2019-09-20 00:12:00,126.0,34FCB96C1680,168.131.181.115,14205E224242,2019,9,20,0,10
6,200011203,도서관열람실,2019-09-20 06:33:00,2019-09-20 06:35:00,78.0,34FCB96C1680,168.131.181.115,08EE8B24A01F,2019,9,20,6,33
7,200011203,도서관열람실,2019-09-20 06:33:00,2019-09-20 06:35:00,78.0,34FCB96C1680,168.131.181.115,08EE8B24A01F,2019,9,20,6,33
8,110763,도서관열람실,2019-09-20 06:57:00,2019-09-20 07:09:00,738.0,34FCB96C1690,168.131.181.115,484BAA4F261C,2019,9,20,6,57
9,130012,도서관열람실,2019-09-20 07:11:00,2019-09-20 07:11:00,35.0,34FCB96C1690,168.131.181.115,E42B342B9303,2019,9,20,7,11
10,130012,도서관열람실,2019-09-20 07:11:00,2019-09-20 07:11:00,35.0,34FCB96C1690,168.131.181.115,E42B342B9303,2019,9,20,7,11
11,198917,도서관열람실,2019-09-20 07:11:00,2019-09-20 07:11:00,10.0,34FCB96C1680,168.131.181.115,F0DBF80C0140,2019,9,20,7,11
12,134964,도서관열람실,2019-09-20 07:15:00,2019-09-20 07:16:00,86.0,34FCB96C1680,168.131.181.115,D0B128C52C59,2019,9,20,7,15
13,134787,도서관열람실,2019-09-20 07:32:00,2019-09-20 09:35:00,7370.0,34FCB96C1690,168.131.181.115,948BC1541B0A,2019,9,20,7,32
14,155992,도서관열람실,2019-09-20 07:45:00,2019-09-20 11:43:00,14254.0,34FCB96C1690,168.131.181.115,948BC1D9026A,2019,9,20,7,45
15,133025,도서관열람실,2019-09-20 07:49:00,2019-09-20 09:01:00,4355.0,34FCB96C1680,168.131.181.115,948BC14E84B2,2019,9,20,7,49
16,150276,도서관열람실,2019-09-20 07:55:00,2019-09-20 08:28:00,1958.0,34FCB96C1680,168.131.181.115,9800C63B6D11,2019,9,20,7,55
17,151253,도서관열람실,2019-09-20 07:59:00,2019-09-20 08:00:00,72.0,34FCB96C1690,168.131.181.115,647BCEB917B2,2019,9,20,7,59
18,151782,도서관열람실,2019-09-20 08:02:00,2019-09-20 08:02:00,30.0,34FCB96C1690,168.131.181.115,886B6E27E0B5,2019,9,20,8,2
19,130050,도서관열람실,2019-09-20 08:05:00,2019-09-20 08:07:00,71.0,34FCB96C1680,168.131.181.115,60A37D7E01D8,2019,9,20,8,5
20,122567,도서관열람실,2019-09-20 08:08:00,2019-09-20 08:10:00,137.0,34FCB96C1680,168.131.181.115,842E27820BF9,2019,9,20,8,8
21,131528,도서관열람실,2019-09-20 08:12:00,2019-09-20 08:19:00,405.0,34FCB96C1680,168.131.181.115,749EAF17113F,2019,9,20,8,12
22,92408,도서관열람실,2019-09-20 08:12:00,2019-09-20 08:17:00,286.0,34FCB96C1690,168.131.181.115,F8E61ACB6C67,2019,9,20,8,12
23,134029,도서관열람실,2019-09-20 08:12:00,2019-09-20 08:13:00,36.0,34FCB96C1680,168.131.181.115,C0B658D09C53,2019,9,20,8,12
24,93587,도서관열람실,2019-09-20 08:13:00,2019-09-20 11:27:00,11633.0,34FCB96C1680,168.131.181.115,8498661F3533,2019,9,20,8,13
25,160342,도서관열람실,2019-09-20 08:20:00,2019-09-20 08:20:00,41.0,34FCB96C1690,168.131.181.115,F05B7B4A0585,2019,9,20,8,20
26,151253,도서관열람실,2019-09-20 08:31:00,2019-09-20 08:33:00,130.0,34FCB96C1690,168.131.181.115,647BCEB917B2,2019,9,20,8,31
27,73713,도서관열람실,2019-09-20 08:32:00,2019-09-20 08:35:00,187.0,34FCB96C1690,168.131.181.115,685ACF97B442,2019,9,20,8,32
28,144056,도서관열람실,2019-09-20 08:34:00,2019-09-20 08:36:00,94.0,34FCB96C1680,168.131.181.115,74B587675C01,2019,9,20,8,34
29,161797,도서관열람실,2019-09-20 08:36:00,2019-09-20 08:39:00,150.0,34FCB96C1680,168.131.181.115,4C74BFA2CE82,2019,9,20,8,36
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16225,162198,도서관열람실,2019-10-17 23:06:00,2019-10-17 23:10:00,207.0,34FCB96C1690,168.131.181.115,F895EA3A47AF,2019,10,17,23,6
16226,170817,도서관열람실,2019-10-17 23:07:00,2019-10-17 23:08:00,60.0,34FCB96C1690,168.131.181.115,948BC1E7B44C,2019,10,17,23,7
16227,192410,도서관열람실,2019-10-17 23:08:00,2019-10-17 23:25:00,1016.0,34FCB96C1690,168.131.181.115,003DE8E9AF15,2019,10,17,23,8
16228,161360,도서관열람실,2019-10-17 23:13:00,2019-10-17 23:14:00,31.0,34FCB96C1690,168.131.181.115,08AED644F8DB,2019,10,17,23,13
16229,121725,도서관열람실,2019-10-17 23:19:00,2019-10-17 23:29:00,605.0,34FCB96C1690,168.131.181.115,D4909C7C516B,2019,10,17,23,19
16230,104867,도서관열람실,2019-10-17 23:20:00,2019-10-17 23:22:00,133.0,34FCB96C1690,168.131.181.115,C8FF2836A60F,2019,10,17,23,20
16231,191694,도서관열람실,2019-10-17 23:20:00,2019-10-17 23:21:00,50.0,34FCB96C1690,168.131.181.115,F895EA3B5A44,2019,10,17,23,20
16232,164737,도서관열람실,2019-10-17 23:21:00,2019-10-17 23:22:00,60.0,34FCB96C1690,168.131.181.115,FC183CA10FEF,2019,10,17,23,21
16233,160435,도서관열람실,2019-10-17 23:23:00,2019-10-17 23:24:00,33.0,34FCB96C1690,168.131.181.115,E4B2FB4BD24A,2019,10,17,23,23
16234,164765,도서관열람실,2019-10-17 23:24:00,2019-10-17 23:25:00,71.0,34FCB96C1680,168.131.181.115,08EE8B2D77C1,2019,10,17,23,24
16235,163955,도서관열람실,2019-10-17 23:28:00,2019-10-17 23:31:00,191.0,34FCB96C1690,168.131.181.115,D81C79E3C7DD,2019,10,17,23,28
16236,123685,도서관열람실,2019-10-17 23:29:00,2019-10-17 23:32:00,197.0,34FCB96C1680,168.131.181.115,9476B714CB7D,2019,10,17,23,29
16237,191853,도서관열람실,2019-10-17 23:30:00,2019-10-17 23:31:00,91.0,34FCB96C1690,168.131.181.115,08AED6F8BB75,2019,10,17,23,30
16238,181337,도서관열람실,2019-10-17 23:32:00,2019-10-17 23:32:00,32.0,34FCB96C1690,168.131.181.115,4C6BE89B6FEA,2019,10,17,23,32
16239,141055,도서관열람실,2019-10-17 23:37:00,2019-10-17 23:38:00,47.0,34FCB96C1690,168.131.181.115,58404EDB7334,2019,10,17,23,37
16240,145851,도서관열람실,2019-10-17 23:38:00,2019-10-17 23:56:00,1070.0,34FCB96C1680,168.131.181.115,9810E85C1849,2019,10,17,23,38
16241,164753,도서관열람실,2019-10-17 23:39:00,2019-10-17 23:43:00,189.0,34FCB96C1680,168.131.181.115,64C2DE514B76,2019,10,17,23,39
16242,141055,도서관열람실,2019-10-17 23:39:00,2019-10-17 23:43:00,201.0,34FCB96C1690,168.131.181.115,58404EDB7334,2019,10,17,23,39
16243,182280,도서관열람실,2019-10-17 23:41:00,2019-10-17 23:42:00,40.0,34FCB96C1690,168.131.181.115,C0B6580F39C7,2019,10,17,23,41
16244,102745,도서관열람실,2019-10-17 23:45:00,2019-10-17 23:47:00,68.0,34FCB96C1680,168.131.181.115,74C63B72DD77,2019,10,17,23,45
16245,163048,도서관열람실,2019-10-17 23:50:00,2019-10-17 23:54:00,224.0,34FCB96C1690,168.131.181.115,F01898CBFE01,2019,10,17,23,50
16246,173050,도서관열람실,2019-10-17 23:50:00,2019-10-17 23:51:00,34.0,34FCB96C1690,168.131.181.115,549963BC0538,2019,10,17,23,50
16247,162641,도서관열람실,2019-10-17 23:51:00,2019-10-17 23:52:00,51.0,34FCB96C1680,168.131.181.115,5499635E3377,2019,10,17,23,51
16248,162965,도서관열람실,2019-10-17 23:51:00,2019-10-17 23:52:00,34.0,34FCB96C1680,168.131.181.115,A82BB9C83A94,2019,10,17,23,51
16249,171864,도서관열람실,2019-10-17 23:52:00,2019-10-17 23:55:00,192.0,34FCB96C1690,168.131.181.115,80B03DBCE721,2019,10,17,23,52
16250,145531,도서관열람실,2019-10-17 23:53:00,2019-10-17 23:59:00,310.0,34FCB96C1680,168.131.181.115,7C0191CAEB2F,2019,10,17,23,53
16251,145531,도서관열람실,2019-10-17 23:54:00,2019-10-17 23:55:00,61.0,34FCB96C1680,168.131.181.115,F884F2BBB9E1,2019,10,17,23,54
16252,184576,도서관열람실,2019-10-17 23:57:00,2019-10-18 00:00:00,134.0,34FCB96C1680,168.131.181.115,948BC14E5498,2019,10,17,23,57
16253,184576,도서관열람실,2019-10-17 23:58:00,2019-10-17 23:58:00,44.0,34FCB96C1690,168.131.181.115,34A8EBCA37AC,2019,10,17,23,58
16254,120148,도서관열람실,2019-10-17 23:58:00,2019-10-17 23:59:00,56.0,34FCB96C1680,168.131.181.115,F0EE1044E8AE,2019,10,17,23,58

In [14]:
date_data =pd.DataFrame()
date_data.loc[:,'date']=pd.Series(pd.date_range("2019-9-20 00:00", "2019-9-25 00:00", freq="H"))
date_data['all_num']=0

date_data['datetime'] = pd.to_datetime(date_data['date'])
date_data = date_data.set_index("datetime")
date_data.head(-1)

                                   date  all_num
datetime
2019-09-20 00:00:00 2019-09-20 00:00:00        0
2019-09-20 01:00:00 2019-09-20 01:00:00        0
2019-09-20 02:00:00 2019-09-20 02:00:00        0
2019-09-20 03:00:00 2019-09-20 03:00:00        0
2019-09-20 04:00:00 2019-09-20 04:00:00        0
...                                 ...      ...
2019-09-24 19:00:00 2019-09-24 19:00:00        0
2019-09-24 20:00:00 2019-09-24 20:00:00        0
2019-09-24 21:00:00 2019-09-24 21:00:00        0
2019-09-24 22:00:00 2019-09-24 22:00:00        0
2019-09-24 23:00:00 2019-09-24 23:00:00        0

[120 rows x 2 columns]

In [15]:
date_data.head(5)

                                   date  all_num
datetime
2019-09-20 00:00:00 2019-09-20 00:00:00        0
2019-09-20 01:00:00 2019-09-20 01:00:00        0
2019-09-20 02:00:00 2019-09-20 02:00:00        0
2019-09-20 03:00:00 2019-09-20 03:00:00        0
2019-09-20 04:00:00 2019-09-20 04:00:00        0

In [16]:
import datetime
timeStr = '2019-09-21 12:11:32'
Thistime = datetime.datetime.strptime(timeStr, '%Y-%m-%d %H:%M:%S')
yourDatetime = Thistime.replace(hour=Thistime.hour+1, minute=0, second=0)
print(yourDatetime)
ex = pd.to_datetime(yourDatetime, infer_datetime_format=True)
print(ex)

2019-09-21 13:00:00
2019-09-21 13:00:00

In [17]:
import sys
for idx1, row1 in ap_data.iterrows():
    #print(row1.acctsessiontime)
    for i in range(int(row1.acctsessiontime)//3600 + 1):
        date_data.loc[(date_data.index.hour==row1.acctstarttime_hour+i) & (date_data.index.day==row1.acctstarttime_day),'all_num']+=1
        #print(i)
        #print(row1.acctstarttime_hour, row1.acctstarttime_year)
        #date_data.ix[(row1.'acctstarttime_hour'  date_data.ix[시간단위 자르기(row1.)+i(1시간 추가)]['allnum']+=1

In [18]:
date_data.head(50)

                                   date  all_num
datetime
2019-09-20 00:00:00 2019-09-20 00:00:00        6
2019-09-20 01:00:00 2019-09-20 01:00:00        0
2019-09-20 02:00:00 2019-09-20 02:00:00        0
2019-09-20 03:00:00 2019-09-20 03:00:00        0
2019-09-20 04:00:00 2019-09-20 04:00:00        0
2019-09-20 05:00:00 2019-09-20 05:00:00        0
2019-09-20 06:00:00 2019-09-20 06:00:00        3
2019-09-20 07:00:00 2019-09-20 07:00:00        9
2019-09-20 08:00:00 2019-09-20 08:00:00       24
2019-09-20 09:00:00 2019-09-20 09:00:00       31
2019-09-20 10:00:00 2019-09-20 10:00:00       32
2019-09-20 11:00:00 2019-09-20 11:00:00       34
2019-09-20 12:00:00 2019-09-20 12:00:00       52
2019-09-20 13:00:00 2019-09-20 13:00:00       27
2019-09-20 14:00:00 2019-09-20 14:00:00       33
2019-09-20 15:00:00 2019-09-20 15:00:00       54
2019-09-20 16:00:00 2019-09-20 16:00:00       61
2019-09-20 17:00:00 2019-09-20 17:00:00       52
2019-09-20 18:00:00 2019-09-20 18:00:00       57
2019-09-20 19:00:00 2019-09-20 19:00:00       35
2019-09-20 20:00:00 2019-09-20 20:00:00       31
2019-09-20 21:00:00 2019-09-20 21:00:00       29
2019-09-20 22:00:00 2019-09-20 22:00:00       16
2019-09-20 23:00:00 2019-09-20 23:00:00       14
2019-09-21 00:00:00 2019-09-21 00:00:00        4
2019-09-21 01:00:00 2019-09-21 01:00:00        0
2019-09-21 02:00:00 2019-09-21 02:00:00        0
2019-09-21 03:00:00 2019-09-21 03:00:00        0
2019-09-21 04:00:00 2019-09-21 04:00:00        0
2019-09-21 05:00:00 2019-09-21 05:00:00        0
2019-09-21 06:00:00 2019-09-21 06:00:00        4
2019-09-21 07:00:00 2019-09-21 07:00:00        5
2019-09-21 08:00:00 2019-09-21 08:00:00       14
2019-09-21 09:00:00 2019-09-21 09:00:00       11
2019-09-21 10:00:00 2019-09-21 10:00:00       27
2019-09-21 11:00:00 2019-09-21 11:00:00       20
2019-09-21 12:00:00 2019-09-21 12:00:00       37
2019-09-21 13:00:00 2019-09-21 13:00:00       30
2019-09-21 14:00:00 2019-09-21 14:00:00       33
2019-09-21 15:00:00 2019-09-21 15:00:00       33
2019-09-21 16:00:00 2019-09-21 16:00:00       36
2019-09-21 17:00:00 2019-09-21 17:00:00       39
2019-09-21 18:00:00 2019-09-21 18:00:00       51
2019-09-21 19:00:00 2019-09-21 19:00:00       25
2019-09-21 20:00:00 2019-09-21 20:00:00       21
2019-09-21 21:00:00 2019-09-21 21:00:00       18
2019-09-21 22:00:00 2019-09-21 22:00:00        9
2019-09-21 23:00:00 2019-09-21 23:00:00        7
2019-09-22 00:00:00 2019-09-22 00:00:00        0
2019-09-22 01:00:00 2019-09-22 01:00:00        0

In [19]:
date_data.to_excel('exact_data_910_log_3.xlsx')