In [1]:
import pandas as pd
import numpy as np

In [2]:
ap_data = pd.read_excel("exact_data.xlsx")

In [3]:
ap_data.head(-1)

,Unnamed: 0,username,place,acctstarttime,acctstoptime,acctsessiontime,calledstationid,ipaddress,callingstationid,acctstarttime_year,acctstarttime_month,acctstarttime_day,acctstarttime_hour,acctstarttime_minute
0,0,NaN,도서관열람실,2019-09-20 00:00:00,2019-09-20 00:02:00,160,34FCB96AB8E0,168.131.181.120,382DD1579B2F,2019,9,20,0,0
1,1,NaN,도서관열람실,2019-09-20 00:00:00,2019-09-20 00:01:00,40,34FCB96C1690,168.131.181.115,9CE65E074BB4,2019,9,20,0,0
2,2,NaN,도서관열람실,2019-09-20 00:00:00,2019-09-20 00:02:00,160,34FCB96AB8E0,168.131.181.120,382DD1579B2F,2019,9,20,0,0
3,3,NaN,도서관열람실,2019-09-20 00:00:00,2019-09-20 00:01:00,40,34FCB96C1690,168.131.181.115,9CE65E074BB4,2019,9,20,0,0
4,4,151616,도서관열람실,2019-09-20 00:00:00,2019-09-20 00:02:00,160,34FCB96AB8E0,168.131.181.120,382DD1579B2F,2019,9,20,0,0
5,5,163671,도서관열람실,2019-09-20 00:00:00,2019-09-20 00:01:00,40,34FCB96C1690,168.131.181.115,9CE65E074BB4,2019,9,20,0,0
6,6,NaN,도서관열람실,2019-09-20 00:02:00,2019-09-20 00:05:00,175,34FCB96AA300,168.131.181.116,D0B1289F9569,2019,9,20,0,2
7,7,NaN,도서관열람실,2019-09-20 00:02:00,2019-09-20 00:03:00,23,34FCB96C1690,168.131.181.115,B4F7A1C2F002,2019,9,20,0,2
8,8,NaN,도서관열람실,2019-09-20 00:02:00,2019-09-20 00:03:00,23,34FCB96C1690,168.131.181.115,B4F7A1C2F002,2019,9,20,0,2
9,9,NaN,도서관열람실,2019-09-20 00:02:00,2019-09-20 00:05:00,175,34FCB96AA300,168.131.181.116,D0B1289F9569,2019,9,20,0,2
10,10,161737,도서관열람실,2019-09-20 00:02:00,2019-09-20 00:03:00,23,34FCB96C1690,168.131.181.115,B4F7A1C2F002,2019,9,20,0,2
11,11,183752,도서관열람실,2019-09-20 00:02:00,2019-09-20 00:05:00,175,34FCB96AA300,168.131.181.116,D0B1289F9569,2019,9,20,0,2
12,12,NaN,도서관열람실,2019-09-20 00:03:00,2019-09-20 00:04:00,99,34FCB96C1680,168.131.181.115,BCE63F1E4F96,2019,9,20,0,3
13,13,NaN,도서관열람실,2019-09-20 00:03:00,2019-09-20 00:04:00,99,34FCB96C1680,168.131.181.115,BCE63F1E4F96,2019,9,20,0,3
14,14,NaN,도서관열람실,2019-09-20 00:03:00,2019-09-20 00:04:00,99,34FCB96C1680,168.131.181.115,BCE63F1E4F96,2019,9,20,0,3
15,15,NaN,도서관열람실,2019-09-20 00:04:00,2019-09-20 00:09:00,329,34FCB96A9090,168.131.181.113,886B6E27E0B5,2019,9,20,0,4
16,16,NaN,도서관열람실,2019-09-20 00:04:00,2019-09-20 00:09:00,329,34FCB96A9090,168.131.181.113,886B6E27E0B5,2019,9,20,0,4
17,17,151782,도서관열람실,2019-09-20 00:04:00,2019-09-20 00:09:00,329,34FCB96A9090,168.131.181.113,886B6E27E0B5,2019,9,20,0,4
18,18,NaN,도서관열람실,2019-09-20 00:05:00,2019-09-20 00:07:00,147,34FCB96A9080,168.131.181.113,BCE63F1E4F96,2019,9,20,0,5
19,19,NaN,도서관열람실,2019-09-20 00:05:00,2019-09-20 00:06:00,65,34FCB96C1960,168.131.181.119,D0B12866743B,2019,9,20,0,5
20,20,NaN,도서관열람실,2019-09-20 00:05:00,2019-09-20 00:07:00,147,34FCB96A9080,168.131.181.113,BCE63F1E4F96,2019,9,20,0,5
21,21,NaN,도서관열람실,2019-09-20 00:05:00,2019-09-20 00:06:00,65,34FCB96C1960,168.131.181.119,D0B12866743B,2019,9,20,0,5
22,22,123111,도서관열람실,2019-09-20 00:05:00,2019-09-20 00:07:00,147,34FCB96A9080,168.131.181.113,BCE63F1E4F96,2019,9,20,0,5
23,23,165605,도서관열람실,2019-09-20 00:05:00,2019-09-20 00:06:00,65,34FCB96C1960,168.131.181.119,D0B12866743B,2019,9,20,0,5
24,24,NaN,도서관열람실,2019-09-20 00:06:00,2019-09-20 00:07:00,37,34FCB96C1690,168.131.181.115,60F4456A8F8E,2019,9,20,0,6
25,25,NaN,도서관열람실,2019-09-20 00:06:00,2019-09-20 00:07:00,46,34FCB96C1680,168.131.181.115,D0B12866743B,2019,9,20,0,6
26,26,NaN,도서관열람실,2019-09-20 00:06:00,2019-09-20 00:07:00,46,34FCB96C1680,168.131.181.115,D0B12866743B,2019,9,20,0,6
27,27,NaN,도서관열람실,2019-09-20 00:06:00,2019-09-20 00:07:00,37,34FCB96C1690,168.131.181.115,60F4456A8F8E,2019,9,20,0,6
28,28,NaN,도서관열람실,2019-09-20 00:06:00,2019-09-20 00:07:00,46,34FCB96C1680,168.131.181.115,D0B12866743B,2019,9,20,0,6
29,29,62862,도서관열람실,2019-09-20 00:06:00,2019-09-20 00:07:00,37,34FCB96C1690,168.131.181.115,60F4456A8F8E,2019,9,20,0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24722,24722,163916,도서관열람실,2019-09-26 23:34:00,2019-09-26 23:36:00,133,34FCB96C1C10,168.131.181.117,D46D6DEA68E8,2019,9,26,23,34
24723,24723,190226,도서관별관(백도),2019-09-26 23:34:00,2019-09-26 23:37:00,154,34FCB96AF2E0,168.131.181.102,4C569D6456E4,2019,9,26,23,34
24724,24724,92082,도서관열람실,2019-09-26 23:35:00,2019-09-26 23:36:00,66,34FCB96A9090,168.131.181.113,BCB863AE345D,2019,9,26,23,35
24725,24725,123768,도서관열람실,2019-09-26 23:35:00,2019-09-26 23:36:00,53,34FCB96A9090,168.131.181.113,50770543776D,2019,9,26,23,35
24726,24726,114502,도서관열람실,2019-09-26 23:38:00,2019-09-26 23:39:00,23,34FCB96C1690,168.131.181.115,74B587B15173,2019,9,26,23,38
24727,24727,177135,도서관열람실,2019-09-26 23:39:00,2019-09-26 23:44:00,351,34FCB96C1690,168.131.181.115,647BCEAC02F2,2019,9,26,23,39
24728,24728,114502,도서관별관(백도),2019-09-26 23:39:00,2019-09-26 23:40:00,33,34FCB96AF2F0,168.131.181.102,74B587B15173,2019,9,26,23,39
24729,24729,155820,도서관열람실,2019-09-26 23:41:00,2019-09-26 23:42:00,100,34FCB96C1680,168.131.181.115,D0817A716E54,2019,9,26,23,41
24730,24730,152191,도서관별관(백도),2019-09-26 23:41:00,2019-09-26 23:43:00,136,34FCB96AF2F0,168.131.181.102,5077056DED69,2019,9,26,23,41
24731,24731,163830,도서관열람실,2019-09-26 23:43:00,2019-09-26 23:44:00,89,34FCB96C1690,168.131.181.115,C4618B9A7199,2019,9,26,23,43
24732,24732,155809,도서관별관(백도),2019-09-26 23:44:00,2019-09-26 23:45:00,35,34FCB96A9D20,168.131.181.99,08AED6168301,2019,9,26,23,44
24733,24733,101519,도서관열람실,2019-09-26 23:44:00,2019-09-26 23:45:00,45,34FCB96C1680,168.131.181.115,C4618B324F18,2019,9,26,23,44
24734,24734,145644,도서관열람실,2019-09-26 23:44:00,2019-09-27 00:02:00,1029,34FCB96C1680,168.131.181.115,9476B7CFC0EB,2019,9,26,23,44
24735,24735,177135,도서관별관(백도),2019-09-26 23:44:00,2019-09-26 23:45:00,48,34FCB96A9D20,168.131.181.99,647BCEAC02F2,2019,9,26,23,44
24736,24736,182638,도서관열람실,2019-09-26 23:45:00,2019-09-26 23:46:00,69,34FCB96C1990,168.131.181.114,5077056D82F1,2019,9,26,23,45
24737,24737,163830,도서관별관(백도),2019-09-26 23:45:00,2019-09-26 23:45:00,29,34FCB96AF2F0,168.131.181.102,C4618B9A7199,2019,9,26,23,45
24738,24738,145786,도서관열람실,2019-09-26 23:46:00,2019-09-27 00:09:00,1353,34FCB96A9A10,168.131.181.118,80B03D3A1DFD,2019,9,26,23,46
24739,24739,91936,도서관열람실,2019-09-26 23:47:00,2019-09-26 23:52:00,255,34FCB96C1C10,168.131.181.117,EC2CE2930CC3,2019,9,26,23,47
24740,24740,144085,도서관열람실,2019-09-26 23:49:00,2019-09-26 23:50:00,97,34FCB96C1C00,168.131.181.117,BCFED921648F,2019,9,26,23,49
24741,24741,101519,도서관열람실,2019-09-26 23:49:00,2019-09-26 23:50:00,43,34FCB96C1680,168.131.181.115,C4618B324F18,2019,9,26,23,49
24742,24742,101519,도서관별관(백도),2019-09-26 23:49:00,2019-09-26 23:55:00,354,34FCB96AF2E0,168.131.181.102,0C72D90226E1,2019,9,26,23,49
24743,24743,183802,도서관열람실,2019-09-26 23:50:00,2019-09-26 23:51:00,43,34FCB96AA300,168.131.181.116,F83880EF054B,2019,9,26,23,50
24744,24744,101519,도서관별관(백도),2019-09-26 23:50:00,2019-09-26 23:53:00,164,34FCB96A9D20,168.131.181.99,C4618B324F18,2019,9,26,23,50
24745,24745,151481,도서관별관(백도),2019-09-26 23:50:00,2019-09-26 23:57:00,429,34FCB96AF2F0,168.131.181.102,D02B20C8CF51,2019,9,26,23,50
24746,24746,188846,도서관별관(백도),2019-09-26 23:51:00,2019-09-26 23:52:00,65,34FCB96A96C0,168.131.181.101,58C93561E786,2019,9,26,23,51
24747,24747,160999,도서관열람실,2019-09-26 23:52:00,2019-09-26 23:54:00,147,34FCB96C1990,168.131.181.114,E42B3430607E,2019,9,26,23,52
24748,24748,sq,도서관,2019-09-26 23:53:00,2019-09-27 00:13:00,1196,24DEC6A55B88,168.131.186.2,A82BB9B2FA08,2019,9,26,23,53
24749,24749,115760,도서관열람실,2019-09-26 23:53:00,2019-09-27 00:01:00,433,34FCB96AB8F0,168.131.181.120,D4E6B74D7877,2019,9,26,23,53
24750,24750,155809,도서관별관(백도),2019-09-26 23:57:00,2019-09-26 23:58:00,59,34FCB96AF2F0,168.131.181.102,08AED6168301,2019,9,26,23,57
24751,24751,151616,도서관별관(백도),2019-09-26 23:58:00,2019-09-27 00:00:00,102,34FCB96AF2F0,168.131.181.102,382DD1579B2F,2019,9,26,23,58

In [4]:
ap_data = ap_data.loc[ap_data['username'].notnull(),:]

In [5]:
ap_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20293 entries, 4 to 24752
Data columns (total 14 columns):
Unnamed: 0              20293 non-null int64
username                20293 non-null object
place                   20293 non-null object
acctstarttime           20293 non-null datetime64[ns]
acctstoptime            20293 non-null datetime64[ns]
acctsessiontime         20293 non-null int64
calledstationid         20293 non-null object
ipaddress               20293 non-null object
callingstationid        20293 non-null object
acctstarttime_year      20293 non-null int64
acctstarttime_month     20293 non-null int64
acctstarttime_day       20293 non-null int64
acctstarttime_hour      20293 non-null int64
acctstarttime_minute    20293 non-null int64
dtypes: datetime64[ns](2), int64(7), object(5)
memory usage: 2.3+ MB

In [6]:
ap_data.head()

,Unnamed: 0,username,place,acctstarttime,acctstoptime,acctsessiontime,calledstationid,ipaddress,callingstationid,acctstarttime_year,acctstarttime_month,acctstarttime_day,acctstarttime_hour,acctstarttime_minute
4,4,151616,도서관열람실,2019-09-20 00:00:00,2019-09-20 00:02:00,160,34FCB96AB8E0,168.131.181.120,382DD1579B2F,2019,9,20,0,0
5,5,163671,도서관열람실,2019-09-20 00:00:00,2019-09-20 00:01:00,40,34FCB96C1690,168.131.181.115,9CE65E074BB4,2019,9,20,0,0
10,10,161737,도서관열람실,2019-09-20 00:02:00,2019-09-20 00:03:00,23,34FCB96C1690,168.131.181.115,B4F7A1C2F002,2019,9,20,0,2
11,11,183752,도서관열람실,2019-09-20 00:02:00,2019-09-20 00:05:00,175,34FCB96AA300,168.131.181.116,D0B1289F9569,2019,9,20,0,2
17,17,151782,도서관열람실,2019-09-20 00:04:00,2019-09-20 00:09:00,329,34FCB96A9090,168.131.181.113,886B6E27E0B5,2019,9,20,0,4

In [7]:
ap_data = ap_data.reset_index(drop=True)

In [8]:
ap_data = ap_data.drop('Unnamed: 0', axis = 1)

In [9]:
ap_data.head()

,username,place,acctstarttime,acctstoptime,acctsessiontime,calledstationid,ipaddress,callingstationid,acctstarttime_year,acctstarttime_month,acctstarttime_day,acctstarttime_hour,acctstarttime_minute
0,151616,도서관열람실,2019-09-20 00:00:00,2019-09-20 00:02:00,160,34FCB96AB8E0,168.131.181.120,382DD1579B2F,2019,9,20,0,0
1,163671,도서관열람실,2019-09-20 00:00:00,2019-09-20 00:01:00,40,34FCB96C1690,168.131.181.115,9CE65E074BB4,2019,9,20,0,0
2,161737,도서관열람실,2019-09-20 00:02:00,2019-09-20 00:03:00,23,34FCB96C1690,168.131.181.115,B4F7A1C2F002,2019,9,20,0,2
3,183752,도서관열람실,2019-09-20 00:02:00,2019-09-20 00:05:00,175,34FCB96AA300,168.131.181.116,D0B1289F9569,2019,9,20,0,2
4,151782,도서관열람실,2019-09-20 00:04:00,2019-09-20 00:09:00,329,34FCB96A9090,168.131.181.113,886B6E27E0B5,2019,9,20,0,4

In [10]:
#7열이라고 예상되는 것만 뽑음

ap_data = ap_data.loc[((ap_data['calledstationid'] == '34FCB96C1C10') | (ap_data['calledstationid'] == '34FCB96C1C00')), :]

In [11]:
ap_data = ap_data.reset_index(drop=True)

In [12]:
ap_data.head(-1)

,username,place,acctstarttime,acctstoptime,acctsessiontime,calledstationid,ipaddress,callingstationid,acctstarttime_year,acctstarttime_month,acctstarttime_day,acctstarttime_hour,acctstarttime_minute
0,121742,도서관열람실,2019-09-20 07:31:00,2019-09-20 09:51:00,8405,34FCB96C1C10,168.131.181.117,3C9509853341,2019,9,20,7,31
1,b7931,도서관열람실,2019-09-20 07:35:00,2019-09-20 07:39:00,227,34FCB96C1C00,168.131.181.117,44783E0C17AA,2019,9,20,7,35
2,176272,도서관열람실,2019-09-20 07:39:00,2019-09-20 10:53:00,11673,34FCB96C1C00,168.131.181.117,9CE6E7CDDA56,2019,9,20,7,39
3,happy00727,도서관열람실,2019-09-20 07:59:00,2019-09-20 08:00:00,50,34FCB96C1C00,168.131.181.117,F8E61AFD6E5F,2019,9,20,7,59
4,122551,도서관열람실,2019-09-20 08:01:00,2019-09-20 08:20:00,1166,34FCB96C1C10,168.131.181.117,88365FB69B0D,2019,9,20,8,1
5,133348,도서관열람실,2019-09-20 08:06:00,2019-09-20 08:42:00,2184,34FCB96C1C10,168.131.181.117,A82BB9D2FD9C,2019,9,20,8,6
6,145804,도서관열람실,2019-09-20 08:06:00,2019-09-20 09:20:00,4391,34FCB96C1C00,168.131.181.117,24F5AA72FB87,2019,9,20,8,6
7,122551,도서관열람실,2019-09-20 08:21:00,2019-09-20 09:29:00,4054,34FCB96C1C10,168.131.181.117,C82158FBF97D,2019,9,20,8,21
8,155544,도서관열람실,2019-09-20 08:22:00,2019-09-20 09:55:00,5525,34FCB96C1C10,168.131.181.117,DC0B34AEDFFD,2019,9,20,8,22
9,8910374,도서관열람실,2019-09-20 08:37:00,2019-09-20 08:38:00,55,34FCB96C1C00,168.131.181.117,D4A33D052AF7,2019,9,20,8,37
10,133575,도서관열람실,2019-09-20 08:40:00,2019-09-20 08:45:00,287,34FCB96C1C00,168.131.181.117,D868C36D1DD1,2019,9,20,8,40
11,133369,도서관열람실,2019-09-20 08:48:00,2019-09-20 09:13:00,1478,34FCB96C1C10,168.131.181.117,548CA0785145,2019,9,20,8,48
12,160893,도서관열람실,2019-09-20 08:56:00,2019-09-20 09:40:00,2668,34FCB96C1C10,168.131.181.117,948BC112B3F8,2019,9,20,8,56
13,193482,도서관열람실,2019-09-20 09:03:00,2019-09-20 11:01:00,7060,34FCB96C1C10,168.131.181.117,BCA58BECA067,2019,9,20,9,3
14,163848,도서관열람실,2019-09-20 09:12:00,2019-09-20 11:26:00,8008,34FCB96C1C10,168.131.181.117,1002B5144295,2019,9,20,9,12
15,145636,도서관열람실,2019-09-20 09:15:00,2019-09-20 12:49:00,12799,34FCB96C1C10,168.131.181.117,0C8BFD9B3903,2019,9,20,9,15
16,133369,도서관열람실,2019-09-20 09:21:00,2019-09-20 09:24:00,206,34FCB96C1C10,168.131.181.117,548CA0785145,2019,9,20,9,21
17,122551,도서관열람실,2019-09-20 09:32:00,2019-09-20 10:51:00,4729,34FCB96C1C10,168.131.181.117,C82158FBF97D,2019,9,20,9,32
18,134787,도서관열람실,2019-09-20 09:35:00,2019-09-20 10:21:00,2788,34FCB96C1C10,168.131.181.117,948BC1541B0A,2019,9,20,9,35
19,70644,도서관열람실,2019-09-20 09:35:00,2019-09-20 09:35:00,21,34FCB96C1C00,168.131.181.117,BCEC5D1D1626,2019,9,20,9,35
20,132104,도서관열람실,2019-09-20 09:43:00,2019-09-20 12:42:00,10744,34FCB96C1C10,168.131.181.117,30E37AE97C7B,2019,9,20,9,43
21,160893,도서관열람실,2019-09-20 09:50:00,2019-09-20 10:45:00,3270,34FCB96C1C10,168.131.181.117,948BC112B3F8,2019,9,20,9,50
22,143333,도서관열람실,2019-09-20 09:52:00,2019-09-20 09:53:00,30,34FCB96C1C10,168.131.181.117,5076AF6F5D24,2019,9,20,9,52
23,133369,도서관열람실,2019-09-20 09:55:00,2019-09-20 11:25:00,5380,34FCB96C1C10,168.131.181.117,548CA0785145,2019,9,20,9,55
24,133851,도서관열람실,2019-09-20 09:56:00,2019-09-20 13:47:00,13875,34FCB96C1C10,168.131.181.117,3052CB684B6D,2019,9,20,9,56
25,141188,도서관열람실,2019-09-20 09:58:00,2019-09-20 09:59:00,71,34FCB96C1C10,168.131.181.117,9CE65E2204BF,2019,9,20,9,58
26,155544,도서관열람실,2019-09-20 09:58:00,2019-09-20 10:52:00,3250,34FCB96C1C10,168.131.181.117,DC0B34AEDFFD,2019,9,20,9,58
27,193321,도서관열람실,2019-09-20 10:05:00,2019-09-20 11:39:00,5666,34FCB96C1C10,168.131.181.117,A0C5896C8A09,2019,9,20,10,5
28,124710,도서관열람실,2019-09-20 10:06:00,2019-09-20 11:44:00,5854,34FCB96C1C10,168.131.181.117,60F6776F35EC,2019,9,20,10,6
29,151782,도서관열람실,2019-09-20 10:12:00,2019-09-20 13:01:00,10102,34FCB96C1C00,168.131.181.117,CCB0DA50513F,2019,9,20,10,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1443,101519,도서관열람실,2019-09-26 20:49:00,2019-09-26 20:49:00,36,34FCB96C1C00,168.131.181.117,C4618B324F18,2019,9,26,20,49
1444,160472,도서관열람실,2019-09-26 20:55:00,2019-09-26 21:21:00,1577,34FCB96C1C10,168.131.181.117,780CB8CB087C,2019,9,26,20,55
1445,173419,도서관열람실,2019-09-26 21:02:00,2019-09-26 21:16:00,835,34FCB96C1C10,168.131.181.117,5C514FA8217C,2019,9,26,21,2
1446,164728,도서관열람실,2019-09-26 21:04:00,2019-09-26 21:41:00,2173,34FCB96C1C10,168.131.181.117,C8FF28E4A387,2019,9,26,21,4
1447,155992,도서관열람실,2019-09-26 21:06:00,2019-09-26 21:08:00,126,34FCB96C1C00,168.131.181.117,948BC1D9026A,2019,9,26,21,6
1448,151164,도서관열람실,2019-09-26 21:10:00,2019-09-26 22:36:00,5173,34FCB96C1C10,168.131.181.117,D46D6DFB5167,2019,9,26,21,10
1449,150276,도서관열람실,2019-09-26 21:11:00,2019-09-26 21:12:00,45,34FCB96C1C00,168.131.181.117,9800C63B6D11,2019,9,26,21,11
1450,155758,도서관열람실,2019-09-26 21:13:00,2019-09-26 21:23:00,614,34FCB96C1C00,168.131.181.117,4C74BFC00655,2019,9,26,21,13
1451,91936,도서관열람실,2019-09-26 21:17:00,2019-09-26 21:18:00,31,34FCB96C1C10,168.131.181.117,EC2CE2930CC3,2019,9,26,21,17
1452,164728,도서관열람실,2019-09-26 21:17:00,2019-09-26 21:42:00,1503,34FCB96C1C10,168.131.181.117,E42B342B905F,2019,9,26,21,17
1453,163619,도서관열람실,2019-09-26 21:25:00,2019-09-26 21:36:00,654,34FCB96C1C10,168.131.181.117,ACF6F7B7BCFD,2019,9,26,21,25
1454,151429,도서관열람실,2019-09-26 21:27:00,2019-09-26 21:28:00,66,34FCB96C1C00,168.131.181.117,5077057C2CBE,2019,9,26,21,27
1455,132341,도서관열람실,2019-09-26 21:31:00,2019-09-26 22:26:00,3331,34FCB96C1C10,168.131.181.117,C4618B9C0064,2019,9,26,21,31
1456,164765,도서관열람실,2019-09-26 21:36:00,2019-09-26 21:37:00,60,34FCB96C1C10,168.131.181.117,74B58791C68F,2019,9,26,21,36
1457,b7931,도서관열람실,2019-09-26 21:38:00,2019-09-26 21:39:00,69,34FCB96C1C00,168.131.181.117,44783E0C17AA,2019,9,26,21,38
1458,134964,도서관열람실,2019-09-26 21:40:00,2019-09-26 21:41:00,66,34FCB96C1C10,168.131.181.117,005B94AF4751,2019,9,26,21,40
1459,155992,도서관열람실,2019-09-26 21:46:00,2019-09-26 21:47:00,33,34FCB96C1C00,168.131.181.117,948BC1D9026A,2019,9,26,21,46
1460,174546,도서관열람실,2019-09-26 21:50:00,2019-09-26 22:25:00,2106,34FCB96C1C10,168.131.181.117,5891CFC248BD,2019,9,26,21,50
1461,162730,도서관열람실,2019-09-26 21:51:00,2019-09-26 21:53:00,79,34FCB96C1C00,168.131.181.117,2CF0A2C39A17,2019,9,26,21,51
1462,142462,도서관열람실,2019-09-26 21:55:00,2019-09-26 22:00:00,301,34FCB96C1C00,168.131.181.117,F8633F14B928,2019,9,26,21,55
1463,134247,도서관열람실,2019-09-26 21:57:00,2019-09-26 22:03:00,391,34FCB96C1C10,168.131.181.117,1002B5C72027,2019,9,26,21,57
1464,133291,도서관열람실,2019-09-26 22:04:00,2019-09-26 22:06:00,114,34FCB96C1C10,168.131.181.117,74EB801EA5C8,2019,9,26,22,4
1465,122296,도서관열람실,2019-09-26 22:05:00,2019-09-26 22:36:00,1850,34FCB96C1C10,168.131.181.117,08F69C0224D5,2019,9,26,22,5
1466,171834,도서관열람실,2019-09-26 22:06:00,2019-09-26 23:44:00,5886,34FCB96C1C10,168.131.181.117,3CA0676352EB,2019,9,26,22,6
1467,132341,도서관열람실,2019-09-26 22:27:00,2019-09-26 22:39:00,772,34FCB96C1C10,168.131.181.117,C4618B9C0064,2019,9,26,22,27
1468,161975,도서관열람실,2019-09-26 22:31:00,2019-09-26 22:36:00,299,34FCB96C1C10,168.131.181.117,08AED68C31F7,2019,9,26,22,31
1469,191368,도서관열람실,2019-09-26 22:42:00,2019-09-26 22:43:00,69,34FCB96C1C10,168.131.181.117,EC2CE2C1978E,2019,9,26,22,42
1470,123092,도서관열람실,2019-09-26 22:59:00,2019-09-26 23:01:00,95,34FCB96C1C10,168.131.181.117,948BC103A33E,2019,9,26,22,59
1471,163916,도서관열람실,2019-09-26 23:34:00,2019-09-26 23:36:00,133,34FCB96C1C10,168.131.181.117,D46D6DEA68E8,2019,9,26,23,34
1472,91936,도서관열람실,2019-09-26 23:47:00,2019-09-26 23:52:00,255,34FCB96C1C10,168.131.181.117,EC2CE2930CC3,2019,9,26,23,47

In [13]:
date_data =pd.DataFrame()
date_data.loc[:,'date']=pd.Series(pd.date_range("2019-9-20 00:00", "2019-9-25 00:00", freq="H"))
date_data['all_num']=0

date_data['datetime'] = pd.to_datetime(date_data['date'])
date_data = date_data.set_index("datetime")
date_data.head(-1)

                                   date  all_num
datetime
2019-09-20 00:00:00 2019-09-20 00:00:00        0
2019-09-20 01:00:00 2019-09-20 01:00:00        0
2019-09-20 02:00:00 2019-09-20 02:00:00        0
2019-09-20 03:00:00 2019-09-20 03:00:00        0
2019-09-20 04:00:00 2019-09-20 04:00:00        0
...                                 ...      ...
2019-09-24 19:00:00 2019-09-24 19:00:00        0
2019-09-24 20:00:00 2019-09-24 20:00:00        0
2019-09-24 21:00:00 2019-09-24 21:00:00        0
2019-09-24 22:00:00 2019-09-24 22:00:00        0
2019-09-24 23:00:00 2019-09-24 23:00:00        0

[120 rows x 2 columns]

In [14]:
date_data.head(5)

                                   date  all_num
datetime
2019-09-20 00:00:00 2019-09-20 00:00:00        0
2019-09-20 01:00:00 2019-09-20 01:00:00        0
2019-09-20 02:00:00 2019-09-20 02:00:00        0
2019-09-20 03:00:00 2019-09-20 03:00:00        0
2019-09-20 04:00:00 2019-09-20 04:00:00        0

In [15]:
import datetime
timeStr = '2019-09-21 12:11:32'
Thistime = datetime.datetime.strptime(timeStr, '%Y-%m-%d %H:%M:%S')
yourDatetime = Thistime.replace(hour=Thistime.hour+1, minute=0, second=0)
print(yourDatetime)
ex = pd.to_datetime(yourDatetime, infer_datetime_format=True)
print(ex)

2019-09-21 13:00:00
2019-09-21 13:00:00

In [16]:
import sys
for idx1, row1 in ap_data.iterrows():
    #print(row1.acctsessiontime)
    for i in range(int(row1.acctsessiontime)//3600 + 1):
        date_data.loc[(date_data.index.hour==row1.acctstarttime_hour+i) & (date_data.index.day==row1.acctstarttime_day),'all_num']+=1
        #print(i)
        #print(row1.acctstarttime_hour, row1.acctstarttime_year)
        #date_data.ix[(row1.'acctstarttime_hour'  date_data.ix[시간단위 자르기(row1.)+i(1시간 추가)]['allnum']+=1

In [17]:
date_data.head(50)

                                   date  all_num
datetime
2019-09-20 00:00:00 2019-09-20 00:00:00        0
2019-09-20 01:00:00 2019-09-20 01:00:00        0
2019-09-20 02:00:00 2019-09-20 02:00:00        0
2019-09-20 03:00:00 2019-09-20 03:00:00        0
2019-09-20 04:00:00 2019-09-20 04:00:00        0
2019-09-20 05:00:00 2019-09-20 05:00:00        0
2019-09-20 06:00:00 2019-09-20 06:00:00        0
2019-09-20 07:00:00 2019-09-20 07:00:00        4
2019-09-20 08:00:00 2019-09-20 08:00:00       11
2019-09-20 09:00:00 2019-09-20 09:00:00       19
2019-09-20 10:00:00 2019-09-20 10:00:00       25
2019-09-20 11:00:00 2019-09-20 11:00:00       29
2019-09-20 12:00:00 2019-09-20 12:00:00       22
2019-09-20 13:00:00 2019-09-20 13:00:00       32
2019-09-20 14:00:00 2019-09-20 14:00:00       36
2019-09-20 15:00:00 2019-09-20 15:00:00       55
2019-09-20 16:00:00 2019-09-20 16:00:00       32
2019-09-20 17:00:00 2019-09-20 17:00:00       29
2019-09-20 18:00:00 2019-09-20 18:00:00       21
2019-09-20 19:00:00 2019-09-20 19:00:00       15
2019-09-20 20:00:00 2019-09-20 20:00:00       11
2019-09-20 21:00:00 2019-09-20 21:00:00       18
2019-09-20 22:00:00 2019-09-20 22:00:00       15
2019-09-20 23:00:00 2019-09-20 23:00:00        6
2019-09-21 00:00:00 2019-09-21 00:00:00        2
2019-09-21 01:00:00 2019-09-21 01:00:00        0
2019-09-21 02:00:00 2019-09-21 02:00:00        0
2019-09-21 03:00:00 2019-09-21 03:00:00        0
2019-09-21 04:00:00 2019-09-21 04:00:00        0
2019-09-21 05:00:00 2019-09-21 05:00:00        0
2019-09-21 06:00:00 2019-09-21 06:00:00        0
2019-09-21 07:00:00 2019-09-21 07:00:00        5
2019-09-21 08:00:00 2019-09-21 08:00:00        6
2019-09-21 09:00:00 2019-09-21 09:00:00       10
2019-09-21 10:00:00 2019-09-21 10:00:00       11
2019-09-21 11:00:00 2019-09-21 11:00:00       13
2019-09-21 12:00:00 2019-09-21 12:00:00       14
2019-09-21 13:00:00 2019-09-21 13:00:00       15
2019-09-21 14:00:00 2019-09-21 14:00:00       26
2019-09-21 15:00:00 2019-09-21 15:00:00       30
2019-09-21 16:00:00 2019-09-21 16:00:00       35
2019-09-21 17:00:00 2019-09-21 17:00:00       22
2019-09-21 18:00:00 2019-09-21 18:00:00       21
2019-09-21 19:00:00 2019-09-21 19:00:00       13
2019-09-21 20:00:00 2019-09-21 20:00:00       16
2019-09-21 21:00:00 2019-09-21 21:00:00       14
2019-09-21 22:00:00 2019-09-21 22:00:00        8
2019-09-21 23:00:00 2019-09-21 23:00:00        3
2019-09-22 00:00:00 2019-09-22 00:00:00        1
2019-09-22 01:00:00 2019-09-22 01:00:00        0

In [18]:
date_data.to_excel('exact_data_92024_log.xlsx')